import { getTranslations, getLocale } from "next-intl/server";
import { PrivacyViewClient } from "../components/privacy-view-client";

export async function PrivacyView() {
  const locale = await getLocale();
  const t = await getTranslations("PublicPrivacy");
  const tBreadcrumb = await getTranslations("Breadcrumb");

  const labels = {
    badge: t("badge"),
    title: t("title"),
    subtitle: t("subtitle"),
    lastUpdated: t("lastUpdated"),
    lastUpdatedDate: t("lastUpdatedDate"),
    q1Title: t("q1Title"),
    q1Content: t("q1Content"),
    q2Title: t("q2Title"),
    q2Content: t("q2Content"),
    q3Title: t("q3Title"),
    q3Content: t("q3Content"),
    q3Company1: t("q3Company1"),
    q3Company2: t("q3Company2"),
    q3Company3: t("q3Company3"),
    q3Email: t("q3Email"),
    q3Phone: t("q3Phone"),
    q3Website: t("q3Website"),
    q4Title: t("q4Title"),
    q4Content: t("q4Content"),
    q4Use1: t("q4Use1"),
    q4Use2: t("q4Use2"),
    q4Use3: t("q4Use3"),
    q5Title: t("q5Title"),
    q5Content: t("q5Content"),
    q5Right1Title: t("q5Right1Title"),
    q5Right1Desc: t("q5Right1Desc"),
    q5Right2Title: t("q5Right2Title"),
    q5Right2Desc: t("q5Right2Desc"),
    q5Right3Title: t("q5Right3Title"),
    q5Right3Desc: t("q5Right3Desc"),
    q5Right4Title: t("q5Right4Title"),
    q5Right4Desc: t("q5Right4Desc"),
    q5Right5Title: t("q5Right5Title"),
    q5Right5Desc: t("q5Right5Desc"),
    q6Title: t("q6Title"),
    q6Content: t("q6Content"),
    q6Obligation1: t("q6Obligation1"),
    q6Obligation2: t("q6Obligation2"),
    q6Obligation3: t("q6Obligation3"),
    q6Footer: t("q6Footer"),
    q7Title: t("q7Title"),
    q7Content: t("q7Content"),
    q8Title: t("q8Title"),
    q8Content: t("q8Content"),
    q8Measure1Title: t("q8Measure1Title"),
    q8Measure1Desc: t("q8Measure1Desc"),
    q8Measure2Title: t("q8Measure2Title"),
    q8Measure2Desc: t("q8Measure2Desc"),
    q8Measure3Title: t("q8Measure3Title"),
    q8Measure3Desc: t("q8Measure3Desc"),
    q9Title: t("q9Title"),
    q9Content: t("q9Content"),
    q10Title: t("q10Title"),
    q10Content: t("q10Content"),
    q11Title: t("q11Title"),
    q11Content: t("q11Content"),
    q11Condition1: t("q11Condition1"),
    q11Condition2: t("q11Condition2"),
    q11Condition3: t("q11Condition3"),
    q11Condition4: t("q11Condition4"),
    q12Title: t("q12Title"),
    q12Content: t("q12Content"),
    q13Title: t("q13Title"),
    q13Content: t("q13Content"),
    contactSectionTitle: t("contactSectionTitle"),
    email: t("email"),
    phone: t("phone"),
    website: t("website"),
    yourRightsTitle: t("yourRightsTitle"),
    yourObligationsTitle: t("yourObligationsTitle"),
    securityTitle: t("securityTitle"),
    dataUsageTitle: t("dataUsageTitle"),
    generalInfoTitle: t("generalInfoTitle"),
    breadcrumbHome: tBreadcrumb("home"),
  };

  return <PrivacyViewClient locale={locale} labels={labels} />;
}
