
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CatalogPage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CatalogPage
 * 
 */
export type CatalogPageModel = runtime.Types.Result.DefaultSelection<Prisma.$CatalogPagePayload>

export type AggregateCatalogPage = {
  _count: CatalogPageCountAggregateOutputType | null
  _avg: CatalogPageAvgAggregateOutputType | null
  _sum: CatalogPageSumAggregateOutputType | null
  _min: CatalogPageMinAggregateOutputType | null
  _max: CatalogPageMaxAggregateOutputType | null
}

export type CatalogPageAvgAggregateOutputType = {
  order: number | null
}

export type CatalogPageSumAggregateOutputType = {
  order: number | null
}

export type CatalogPageMinAggregateOutputType = {
  id: string | null
  catalogId: string | null
  imageUrl: string | null
  alt: string | null
  order: number | null
  createdAt: Date | null
}

export type CatalogPageMaxAggregateOutputType = {
  id: string | null
  catalogId: string | null
  imageUrl: string | null
  alt: string | null
  order: number | null
  createdAt: Date | null
}

export type CatalogPageCountAggregateOutputType = {
  id: number
  catalogId: number
  imageUrl: number
  alt: number
  order: number
  createdAt: number
  _all: number
}


export type CatalogPageAvgAggregateInputType = {
  order?: true
}

export type CatalogPageSumAggregateInputType = {
  order?: true
}

export type CatalogPageMinAggregateInputType = {
  id?: true
  catalogId?: true
  imageUrl?: true
  alt?: true
  order?: true
  createdAt?: true
}

export type CatalogPageMaxAggregateInputType = {
  id?: true
  catalogId?: true
  imageUrl?: true
  alt?: true
  order?: true
  createdAt?: true
}

export type CatalogPageCountAggregateInputType = {
  id?: true
  catalogId?: true
  imageUrl?: true
  alt?: true
  order?: true
  createdAt?: true
  _all?: true
}

export type CatalogPageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CatalogPage to aggregate.
   */
  where?: Prisma.CatalogPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatalogPages to fetch.
   */
  orderBy?: Prisma.CatalogPageOrderByWithRelationInput | Prisma.CatalogPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CatalogPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatalogPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatalogPages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CatalogPages
  **/
  _count?: true | CatalogPageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CatalogPageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CatalogPageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CatalogPageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CatalogPageMaxAggregateInputType
}

export type GetCatalogPageAggregateType<T extends CatalogPageAggregateArgs> = {
      [P in keyof T & keyof AggregateCatalogPage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCatalogPage[P]>
    : Prisma.GetScalarType<T[P], AggregateCatalogPage[P]>
}




export type CatalogPageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CatalogPageWhereInput
  orderBy?: Prisma.CatalogPageOrderByWithAggregationInput | Prisma.CatalogPageOrderByWithAggregationInput[]
  by: Prisma.CatalogPageScalarFieldEnum[] | Prisma.CatalogPageScalarFieldEnum
  having?: Prisma.CatalogPageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CatalogPageCountAggregateInputType | true
  _avg?: CatalogPageAvgAggregateInputType
  _sum?: CatalogPageSumAggregateInputType
  _min?: CatalogPageMinAggregateInputType
  _max?: CatalogPageMaxAggregateInputType
}

export type CatalogPageGroupByOutputType = {
  id: string
  catalogId: string
  imageUrl: string
  alt: string | null
  order: number
  createdAt: Date
  _count: CatalogPageCountAggregateOutputType | null
  _avg: CatalogPageAvgAggregateOutputType | null
  _sum: CatalogPageSumAggregateOutputType | null
  _min: CatalogPageMinAggregateOutputType | null
  _max: CatalogPageMaxAggregateOutputType | null
}

type GetCatalogPageGroupByPayload<T extends CatalogPageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CatalogPageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CatalogPageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CatalogPageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CatalogPageGroupByOutputType[P]>
      }
    >
  >



export type CatalogPageWhereInput = {
  AND?: Prisma.CatalogPageWhereInput | Prisma.CatalogPageWhereInput[]
  OR?: Prisma.CatalogPageWhereInput[]
  NOT?: Prisma.CatalogPageWhereInput | Prisma.CatalogPageWhereInput[]
  id?: Prisma.StringFilter<"CatalogPage"> | string
  catalogId?: Prisma.StringFilter<"CatalogPage"> | string
  imageUrl?: Prisma.StringFilter<"CatalogPage"> | string
  alt?: Prisma.StringNullableFilter<"CatalogPage"> | string | null
  order?: Prisma.IntFilter<"CatalogPage"> | number
  createdAt?: Prisma.DateTimeFilter<"CatalogPage"> | Date | string
  catalog?: Prisma.XOR<Prisma.CatalogScalarRelationFilter, Prisma.CatalogWhereInput>
}

export type CatalogPageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  catalogId?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  alt?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  catalog?: Prisma.CatalogOrderByWithRelationInput
  _relevance?: Prisma.CatalogPageOrderByRelevanceInput
}

export type CatalogPageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CatalogPageWhereInput | Prisma.CatalogPageWhereInput[]
  OR?: Prisma.CatalogPageWhereInput[]
  NOT?: Prisma.CatalogPageWhereInput | Prisma.CatalogPageWhereInput[]
  catalogId?: Prisma.StringFilter<"CatalogPage"> | string
  imageUrl?: Prisma.StringFilter<"CatalogPage"> | string
  alt?: Prisma.StringNullableFilter<"CatalogPage"> | string | null
  order?: Prisma.IntFilter<"CatalogPage"> | number
  createdAt?: Prisma.DateTimeFilter<"CatalogPage"> | Date | string
  catalog?: Prisma.XOR<Prisma.CatalogScalarRelationFilter, Prisma.CatalogWhereInput>
}, "id">

export type CatalogPageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  catalogId?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  alt?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CatalogPageCountOrderByAggregateInput
  _avg?: Prisma.CatalogPageAvgOrderByAggregateInput
  _max?: Prisma.CatalogPageMaxOrderByAggregateInput
  _min?: Prisma.CatalogPageMinOrderByAggregateInput
  _sum?: Prisma.CatalogPageSumOrderByAggregateInput
}

export type CatalogPageScalarWhereWithAggregatesInput = {
  AND?: Prisma.CatalogPageScalarWhereWithAggregatesInput | Prisma.CatalogPageScalarWhereWithAggregatesInput[]
  OR?: Prisma.CatalogPageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CatalogPageScalarWhereWithAggregatesInput | Prisma.CatalogPageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CatalogPage"> | string
  catalogId?: Prisma.StringWithAggregatesFilter<"CatalogPage"> | string
  imageUrl?: Prisma.StringWithAggregatesFilter<"CatalogPage"> | string
  alt?: Prisma.StringNullableWithAggregatesFilter<"CatalogPage"> | string | null
  order?: Prisma.IntWithAggregatesFilter<"CatalogPage"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CatalogPage"> | Date | string
}

export type CatalogPageCreateInput = {
  id?: string
  imageUrl: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
  catalog: Prisma.CatalogCreateNestedOneWithoutPagesInput
}

export type CatalogPageUncheckedCreateInput = {
  id?: string
  catalogId: string
  imageUrl: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type CatalogPageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  catalog?: Prisma.CatalogUpdateOneRequiredWithoutPagesNestedInput
}

export type CatalogPageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  catalogId?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogPageCreateManyInput = {
  id?: string
  catalogId: string
  imageUrl: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type CatalogPageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogPageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  catalogId?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogPageListRelationFilter = {
  every?: Prisma.CatalogPageWhereInput
  some?: Prisma.CatalogPageWhereInput
  none?: Prisma.CatalogPageWhereInput
}

export type CatalogPageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CatalogPageOrderByRelevanceInput = {
  fields: Prisma.CatalogPageOrderByRelevanceFieldEnum | Prisma.CatalogPageOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CatalogPageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  catalogId?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  alt?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CatalogPageAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CatalogPageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  catalogId?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  alt?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CatalogPageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  catalogId?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  alt?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CatalogPageSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CatalogPageCreateNestedManyWithoutCatalogInput = {
  create?: Prisma.XOR<Prisma.CatalogPageCreateWithoutCatalogInput, Prisma.CatalogPageUncheckedCreateWithoutCatalogInput> | Prisma.CatalogPageCreateWithoutCatalogInput[] | Prisma.CatalogPageUncheckedCreateWithoutCatalogInput[]
  connectOrCreate?: Prisma.CatalogPageCreateOrConnectWithoutCatalogInput | Prisma.CatalogPageCreateOrConnectWithoutCatalogInput[]
  createMany?: Prisma.CatalogPageCreateManyCatalogInputEnvelope
  connect?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
}

export type CatalogPageUncheckedCreateNestedManyWithoutCatalogInput = {
  create?: Prisma.XOR<Prisma.CatalogPageCreateWithoutCatalogInput, Prisma.CatalogPageUncheckedCreateWithoutCatalogInput> | Prisma.CatalogPageCreateWithoutCatalogInput[] | Prisma.CatalogPageUncheckedCreateWithoutCatalogInput[]
  connectOrCreate?: Prisma.CatalogPageCreateOrConnectWithoutCatalogInput | Prisma.CatalogPageCreateOrConnectWithoutCatalogInput[]
  createMany?: Prisma.CatalogPageCreateManyCatalogInputEnvelope
  connect?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
}

export type CatalogPageUpdateManyWithoutCatalogNestedInput = {
  create?: Prisma.XOR<Prisma.CatalogPageCreateWithoutCatalogInput, Prisma.CatalogPageUncheckedCreateWithoutCatalogInput> | Prisma.CatalogPageCreateWithoutCatalogInput[] | Prisma.CatalogPageUncheckedCreateWithoutCatalogInput[]
  connectOrCreate?: Prisma.CatalogPageCreateOrConnectWithoutCatalogInput | Prisma.CatalogPageCreateOrConnectWithoutCatalogInput[]
  upsert?: Prisma.CatalogPageUpsertWithWhereUniqueWithoutCatalogInput | Prisma.CatalogPageUpsertWithWhereUniqueWithoutCatalogInput[]
  createMany?: Prisma.CatalogPageCreateManyCatalogInputEnvelope
  set?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  disconnect?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  delete?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  connect?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  update?: Prisma.CatalogPageUpdateWithWhereUniqueWithoutCatalogInput | Prisma.CatalogPageUpdateWithWhereUniqueWithoutCatalogInput[]
  updateMany?: Prisma.CatalogPageUpdateManyWithWhereWithoutCatalogInput | Prisma.CatalogPageUpdateManyWithWhereWithoutCatalogInput[]
  deleteMany?: Prisma.CatalogPageScalarWhereInput | Prisma.CatalogPageScalarWhereInput[]
}

export type CatalogPageUncheckedUpdateManyWithoutCatalogNestedInput = {
  create?: Prisma.XOR<Prisma.CatalogPageCreateWithoutCatalogInput, Prisma.CatalogPageUncheckedCreateWithoutCatalogInput> | Prisma.CatalogPageCreateWithoutCatalogInput[] | Prisma.CatalogPageUncheckedCreateWithoutCatalogInput[]
  connectOrCreate?: Prisma.CatalogPageCreateOrConnectWithoutCatalogInput | Prisma.CatalogPageCreateOrConnectWithoutCatalogInput[]
  upsert?: Prisma.CatalogPageUpsertWithWhereUniqueWithoutCatalogInput | Prisma.CatalogPageUpsertWithWhereUniqueWithoutCatalogInput[]
  createMany?: Prisma.CatalogPageCreateManyCatalogInputEnvelope
  set?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  disconnect?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  delete?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  connect?: Prisma.CatalogPageWhereUniqueInput | Prisma.CatalogPageWhereUniqueInput[]
  update?: Prisma.CatalogPageUpdateWithWhereUniqueWithoutCatalogInput | Prisma.CatalogPageUpdateWithWhereUniqueWithoutCatalogInput[]
  updateMany?: Prisma.CatalogPageUpdateManyWithWhereWithoutCatalogInput | Prisma.CatalogPageUpdateManyWithWhereWithoutCatalogInput[]
  deleteMany?: Prisma.CatalogPageScalarWhereInput | Prisma.CatalogPageScalarWhereInput[]
}

export type CatalogPageCreateWithoutCatalogInput = {
  id?: string
  imageUrl: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type CatalogPageUncheckedCreateWithoutCatalogInput = {
  id?: string
  imageUrl: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type CatalogPageCreateOrConnectWithoutCatalogInput = {
  where: Prisma.CatalogPageWhereUniqueInput
  create: Prisma.XOR<Prisma.CatalogPageCreateWithoutCatalogInput, Prisma.CatalogPageUncheckedCreateWithoutCatalogInput>
}

export type CatalogPageCreateManyCatalogInputEnvelope = {
  data: Prisma.CatalogPageCreateManyCatalogInput | Prisma.CatalogPageCreateManyCatalogInput[]
  skipDuplicates?: boolean
}

export type CatalogPageUpsertWithWhereUniqueWithoutCatalogInput = {
  where: Prisma.CatalogPageWhereUniqueInput
  update: Prisma.XOR<Prisma.CatalogPageUpdateWithoutCatalogInput, Prisma.CatalogPageUncheckedUpdateWithoutCatalogInput>
  create: Prisma.XOR<Prisma.CatalogPageCreateWithoutCatalogInput, Prisma.CatalogPageUncheckedCreateWithoutCatalogInput>
}

export type CatalogPageUpdateWithWhereUniqueWithoutCatalogInput = {
  where: Prisma.CatalogPageWhereUniqueInput
  data: Prisma.XOR<Prisma.CatalogPageUpdateWithoutCatalogInput, Prisma.CatalogPageUncheckedUpdateWithoutCatalogInput>
}

export type CatalogPageUpdateManyWithWhereWithoutCatalogInput = {
  where: Prisma.CatalogPageScalarWhereInput
  data: Prisma.XOR<Prisma.CatalogPageUpdateManyMutationInput, Prisma.CatalogPageUncheckedUpdateManyWithoutCatalogInput>
}

export type CatalogPageScalarWhereInput = {
  AND?: Prisma.CatalogPageScalarWhereInput | Prisma.CatalogPageScalarWhereInput[]
  OR?: Prisma.CatalogPageScalarWhereInput[]
  NOT?: Prisma.CatalogPageScalarWhereInput | Prisma.CatalogPageScalarWhereInput[]
  id?: Prisma.StringFilter<"CatalogPage"> | string
  catalogId?: Prisma.StringFilter<"CatalogPage"> | string
  imageUrl?: Prisma.StringFilter<"CatalogPage"> | string
  alt?: Prisma.StringNullableFilter<"CatalogPage"> | string | null
  order?: Prisma.IntFilter<"CatalogPage"> | number
  createdAt?: Prisma.DateTimeFilter<"CatalogPage"> | Date | string
}

export type CatalogPageCreateManyCatalogInput = {
  id?: string
  imageUrl: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type CatalogPageUpdateWithoutCatalogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogPageUncheckedUpdateWithoutCatalogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogPageUncheckedUpdateManyWithoutCatalogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CatalogPageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  catalogId?: boolean
  imageUrl?: boolean
  alt?: boolean
  order?: boolean
  createdAt?: boolean
  catalog?: boolean | Prisma.CatalogDefaultArgs<ExtArgs>
}, ExtArgs["result"]["catalogPage"]>



export type CatalogPageSelectScalar = {
  id?: boolean
  catalogId?: boolean
  imageUrl?: boolean
  alt?: boolean
  order?: boolean
  createdAt?: boolean
}

export type CatalogPageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "catalogId" | "imageUrl" | "alt" | "order" | "createdAt", ExtArgs["result"]["catalogPage"]>
export type CatalogPageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  catalog?: boolean | Prisma.CatalogDefaultArgs<ExtArgs>
}

export type $CatalogPagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CatalogPage"
  objects: {
    catalog: Prisma.$CatalogPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    catalogId: string
    imageUrl: string
    alt: string | null
    order: number
    createdAt: Date
  }, ExtArgs["result"]["catalogPage"]>
  composites: {}
}

export type CatalogPageGetPayload<S extends boolean | null | undefined | CatalogPageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload, S>

export type CatalogPageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CatalogPageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CatalogPageCountAggregateInputType | true
  }

export interface CatalogPageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CatalogPage'], meta: { name: 'CatalogPage' } }
  /**
   * Find zero or one CatalogPage that matches the filter.
   * @param {CatalogPageFindUniqueArgs} args - Arguments to find a CatalogPage
   * @example
   * // Get one CatalogPage
   * const catalogPage = await prisma.catalogPage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CatalogPageFindUniqueArgs>(args: Prisma.SelectSubset<T, CatalogPageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CatalogPage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CatalogPageFindUniqueOrThrowArgs} args - Arguments to find a CatalogPage
   * @example
   * // Get one CatalogPage
   * const catalogPage = await prisma.catalogPage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CatalogPageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CatalogPageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CatalogPage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageFindFirstArgs} args - Arguments to find a CatalogPage
   * @example
   * // Get one CatalogPage
   * const catalogPage = await prisma.catalogPage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CatalogPageFindFirstArgs>(args?: Prisma.SelectSubset<T, CatalogPageFindFirstArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CatalogPage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageFindFirstOrThrowArgs} args - Arguments to find a CatalogPage
   * @example
   * // Get one CatalogPage
   * const catalogPage = await prisma.catalogPage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CatalogPageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CatalogPageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CatalogPages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CatalogPages
   * const catalogPages = await prisma.catalogPage.findMany()
   * 
   * // Get first 10 CatalogPages
   * const catalogPages = await prisma.catalogPage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const catalogPageWithIdOnly = await prisma.catalogPage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CatalogPageFindManyArgs>(args?: Prisma.SelectSubset<T, CatalogPageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CatalogPage.
   * @param {CatalogPageCreateArgs} args - Arguments to create a CatalogPage.
   * @example
   * // Create one CatalogPage
   * const CatalogPage = await prisma.catalogPage.create({
   *   data: {
   *     // ... data to create a CatalogPage
   *   }
   * })
   * 
   */
  create<T extends CatalogPageCreateArgs>(args: Prisma.SelectSubset<T, CatalogPageCreateArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CatalogPages.
   * @param {CatalogPageCreateManyArgs} args - Arguments to create many CatalogPages.
   * @example
   * // Create many CatalogPages
   * const catalogPage = await prisma.catalogPage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CatalogPageCreateManyArgs>(args?: Prisma.SelectSubset<T, CatalogPageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CatalogPage.
   * @param {CatalogPageDeleteArgs} args - Arguments to delete one CatalogPage.
   * @example
   * // Delete one CatalogPage
   * const CatalogPage = await prisma.catalogPage.delete({
   *   where: {
   *     // ... filter to delete one CatalogPage
   *   }
   * })
   * 
   */
  delete<T extends CatalogPageDeleteArgs>(args: Prisma.SelectSubset<T, CatalogPageDeleteArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CatalogPage.
   * @param {CatalogPageUpdateArgs} args - Arguments to update one CatalogPage.
   * @example
   * // Update one CatalogPage
   * const catalogPage = await prisma.catalogPage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CatalogPageUpdateArgs>(args: Prisma.SelectSubset<T, CatalogPageUpdateArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CatalogPages.
   * @param {CatalogPageDeleteManyArgs} args - Arguments to filter CatalogPages to delete.
   * @example
   * // Delete a few CatalogPages
   * const { count } = await prisma.catalogPage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CatalogPageDeleteManyArgs>(args?: Prisma.SelectSubset<T, CatalogPageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CatalogPages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CatalogPages
   * const catalogPage = await prisma.catalogPage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CatalogPageUpdateManyArgs>(args: Prisma.SelectSubset<T, CatalogPageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CatalogPage.
   * @param {CatalogPageUpsertArgs} args - Arguments to update or create a CatalogPage.
   * @example
   * // Update or create a CatalogPage
   * const catalogPage = await prisma.catalogPage.upsert({
   *   create: {
   *     // ... data to create a CatalogPage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CatalogPage we want to update
   *   }
   * })
   */
  upsert<T extends CatalogPageUpsertArgs>(args: Prisma.SelectSubset<T, CatalogPageUpsertArgs<ExtArgs>>): Prisma.Prisma__CatalogPageClient<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CatalogPages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageCountArgs} args - Arguments to filter CatalogPages to count.
   * @example
   * // Count the number of CatalogPages
   * const count = await prisma.catalogPage.count({
   *   where: {
   *     // ... the filter for the CatalogPages we want to count
   *   }
   * })
  **/
  count<T extends CatalogPageCountArgs>(
    args?: Prisma.Subset<T, CatalogPageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CatalogPageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CatalogPage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CatalogPageAggregateArgs>(args: Prisma.Subset<T, CatalogPageAggregateArgs>): Prisma.PrismaPromise<GetCatalogPageAggregateType<T>>

  /**
   * Group by CatalogPage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogPageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CatalogPageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CatalogPageGroupByArgs['orderBy'] }
      : { orderBy?: CatalogPageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CatalogPageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCatalogPageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CatalogPage model
 */
readonly fields: CatalogPageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CatalogPage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CatalogPageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  catalog<T extends Prisma.CatalogDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CatalogDefaultArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CatalogPage model
 */
export interface CatalogPageFieldRefs {
  readonly id: Prisma.FieldRef<"CatalogPage", 'String'>
  readonly catalogId: Prisma.FieldRef<"CatalogPage", 'String'>
  readonly imageUrl: Prisma.FieldRef<"CatalogPage", 'String'>
  readonly alt: Prisma.FieldRef<"CatalogPage", 'String'>
  readonly order: Prisma.FieldRef<"CatalogPage", 'Int'>
  readonly createdAt: Prisma.FieldRef<"CatalogPage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CatalogPage findUnique
 */
export type CatalogPageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * Filter, which CatalogPage to fetch.
   */
  where: Prisma.CatalogPageWhereUniqueInput
}

/**
 * CatalogPage findUniqueOrThrow
 */
export type CatalogPageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * Filter, which CatalogPage to fetch.
   */
  where: Prisma.CatalogPageWhereUniqueInput
}

/**
 * CatalogPage findFirst
 */
export type CatalogPageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * Filter, which CatalogPage to fetch.
   */
  where?: Prisma.CatalogPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatalogPages to fetch.
   */
  orderBy?: Prisma.CatalogPageOrderByWithRelationInput | Prisma.CatalogPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CatalogPages.
   */
  cursor?: Prisma.CatalogPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatalogPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatalogPages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CatalogPages.
   */
  distinct?: Prisma.CatalogPageScalarFieldEnum | Prisma.CatalogPageScalarFieldEnum[]
}

/**
 * CatalogPage findFirstOrThrow
 */
export type CatalogPageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * Filter, which CatalogPage to fetch.
   */
  where?: Prisma.CatalogPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatalogPages to fetch.
   */
  orderBy?: Prisma.CatalogPageOrderByWithRelationInput | Prisma.CatalogPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CatalogPages.
   */
  cursor?: Prisma.CatalogPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatalogPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatalogPages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CatalogPages.
   */
  distinct?: Prisma.CatalogPageScalarFieldEnum | Prisma.CatalogPageScalarFieldEnum[]
}

/**
 * CatalogPage findMany
 */
export type CatalogPageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * Filter, which CatalogPages to fetch.
   */
  where?: Prisma.CatalogPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CatalogPages to fetch.
   */
  orderBy?: Prisma.CatalogPageOrderByWithRelationInput | Prisma.CatalogPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CatalogPages.
   */
  cursor?: Prisma.CatalogPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CatalogPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CatalogPages.
   */
  skip?: number
  distinct?: Prisma.CatalogPageScalarFieldEnum | Prisma.CatalogPageScalarFieldEnum[]
}

/**
 * CatalogPage create
 */
export type CatalogPageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * The data needed to create a CatalogPage.
   */
  data: Prisma.XOR<Prisma.CatalogPageCreateInput, Prisma.CatalogPageUncheckedCreateInput>
}

/**
 * CatalogPage createMany
 */
export type CatalogPageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CatalogPages.
   */
  data: Prisma.CatalogPageCreateManyInput | Prisma.CatalogPageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CatalogPage update
 */
export type CatalogPageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * The data needed to update a CatalogPage.
   */
  data: Prisma.XOR<Prisma.CatalogPageUpdateInput, Prisma.CatalogPageUncheckedUpdateInput>
  /**
   * Choose, which CatalogPage to update.
   */
  where: Prisma.CatalogPageWhereUniqueInput
}

/**
 * CatalogPage updateMany
 */
export type CatalogPageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CatalogPages.
   */
  data: Prisma.XOR<Prisma.CatalogPageUpdateManyMutationInput, Prisma.CatalogPageUncheckedUpdateManyInput>
  /**
   * Filter which CatalogPages to update
   */
  where?: Prisma.CatalogPageWhereInput
  /**
   * Limit how many CatalogPages to update.
   */
  limit?: number
}

/**
 * CatalogPage upsert
 */
export type CatalogPageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * The filter to search for the CatalogPage to update in case it exists.
   */
  where: Prisma.CatalogPageWhereUniqueInput
  /**
   * In case the CatalogPage found by the `where` argument doesn't exist, create a new CatalogPage with this data.
   */
  create: Prisma.XOR<Prisma.CatalogPageCreateInput, Prisma.CatalogPageUncheckedCreateInput>
  /**
   * In case the CatalogPage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CatalogPageUpdateInput, Prisma.CatalogPageUncheckedUpdateInput>
}

/**
 * CatalogPage delete
 */
export type CatalogPageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  /**
   * Filter which CatalogPage to delete.
   */
  where: Prisma.CatalogPageWhereUniqueInput
}

/**
 * CatalogPage deleteMany
 */
export type CatalogPageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CatalogPages to delete
   */
  where?: Prisma.CatalogPageWhereInput
  /**
   * Limit how many CatalogPages to delete.
   */
  limit?: number
}

/**
 * CatalogPage without action
 */
export type CatalogPageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
}
