
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Catalog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Catalog
 * 
 */
export type CatalogModel = runtime.Types.Result.DefaultSelection<Prisma.$CatalogPayload>

export type AggregateCatalog = {
  _count: CatalogCountAggregateOutputType | null
  _avg: CatalogAvgAggregateOutputType | null
  _sum: CatalogSumAggregateOutputType | null
  _min: CatalogMinAggregateOutputType | null
  _max: CatalogMaxAggregateOutputType | null
}

export type CatalogAvgAggregateOutputType = {
  year: number | null
}

export type CatalogSumAggregateOutputType = {
  year: number | null
}

export type CatalogMinAggregateOutputType = {
  id: string | null
  title: string | null
  slug: string | null
  description: string | null
  year: number | null
  coverImage: string | null
  isActive: boolean | null
  isFeatured: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CatalogMaxAggregateOutputType = {
  id: string | null
  title: string | null
  slug: string | null
  description: string | null
  year: number | null
  coverImage: string | null
  isActive: boolean | null
  isFeatured: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CatalogCountAggregateOutputType = {
  id: number
  title: number
  slug: number
  description: number
  year: number
  coverImage: number
  isActive: number
  isFeatured: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CatalogAvgAggregateInputType = {
  year?: true
}

export type CatalogSumAggregateInputType = {
  year?: true
}

export type CatalogMinAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  description?: true
  year?: true
  coverImage?: true
  isActive?: true
  isFeatured?: true
  createdAt?: true
  updatedAt?: true
}

export type CatalogMaxAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  description?: true
  year?: true
  coverImage?: true
  isActive?: true
  isFeatured?: true
  createdAt?: true
  updatedAt?: true
}

export type CatalogCountAggregateInputType = {
  id?: true
  title?: true
  slug?: true
  description?: true
  year?: true
  coverImage?: true
  isActive?: true
  isFeatured?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CatalogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Catalog to aggregate.
   */
  where?: Prisma.CatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Catalogs to fetch.
   */
  orderBy?: Prisma.CatalogOrderByWithRelationInput | Prisma.CatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Catalogs
  **/
  _count?: true | CatalogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CatalogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CatalogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CatalogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CatalogMaxAggregateInputType
}

export type GetCatalogAggregateType<T extends CatalogAggregateArgs> = {
      [P in keyof T & keyof AggregateCatalog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCatalog[P]>
    : Prisma.GetScalarType<T[P], AggregateCatalog[P]>
}




export type CatalogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CatalogWhereInput
  orderBy?: Prisma.CatalogOrderByWithAggregationInput | Prisma.CatalogOrderByWithAggregationInput[]
  by: Prisma.CatalogScalarFieldEnum[] | Prisma.CatalogScalarFieldEnum
  having?: Prisma.CatalogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CatalogCountAggregateInputType | true
  _avg?: CatalogAvgAggregateInputType
  _sum?: CatalogSumAggregateInputType
  _min?: CatalogMinAggregateInputType
  _max?: CatalogMaxAggregateInputType
}

export type CatalogGroupByOutputType = {
  id: string
  title: string
  slug: string
  description: string | null
  year: number
  coverImage: string | null
  isActive: boolean
  isFeatured: boolean
  createdAt: Date
  updatedAt: Date
  _count: CatalogCountAggregateOutputType | null
  _avg: CatalogAvgAggregateOutputType | null
  _sum: CatalogSumAggregateOutputType | null
  _min: CatalogMinAggregateOutputType | null
  _max: CatalogMaxAggregateOutputType | null
}

type GetCatalogGroupByPayload<T extends CatalogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CatalogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CatalogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CatalogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CatalogGroupByOutputType[P]>
      }
    >
  >



export type CatalogWhereInput = {
  AND?: Prisma.CatalogWhereInput | Prisma.CatalogWhereInput[]
  OR?: Prisma.CatalogWhereInput[]
  NOT?: Prisma.CatalogWhereInput | Prisma.CatalogWhereInput[]
  id?: Prisma.StringFilter<"Catalog"> | string
  title?: Prisma.StringFilter<"Catalog"> | string
  slug?: Prisma.StringFilter<"Catalog"> | string
  description?: Prisma.StringNullableFilter<"Catalog"> | string | null
  year?: Prisma.IntFilter<"Catalog"> | number
  coverImage?: Prisma.StringNullableFilter<"Catalog"> | string | null
  isActive?: Prisma.BoolFilter<"Catalog"> | boolean
  isFeatured?: Prisma.BoolFilter<"Catalog"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Catalog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Catalog"> | Date | string
  pages?: Prisma.CatalogPageListRelationFilter
}

export type CatalogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  year?: Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pages?: Prisma.CatalogPageOrderByRelationAggregateInput
  _relevance?: Prisma.CatalogOrderByRelevanceInput
}

export type CatalogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.CatalogWhereInput | Prisma.CatalogWhereInput[]
  OR?: Prisma.CatalogWhereInput[]
  NOT?: Prisma.CatalogWhereInput | Prisma.CatalogWhereInput[]
  title?: Prisma.StringFilter<"Catalog"> | string
  description?: Prisma.StringNullableFilter<"Catalog"> | string | null
  year?: Prisma.IntFilter<"Catalog"> | number
  coverImage?: Prisma.StringNullableFilter<"Catalog"> | string | null
  isActive?: Prisma.BoolFilter<"Catalog"> | boolean
  isFeatured?: Prisma.BoolFilter<"Catalog"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Catalog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Catalog"> | Date | string
  pages?: Prisma.CatalogPageListRelationFilter
}, "id" | "slug">

export type CatalogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  year?: Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CatalogCountOrderByAggregateInput
  _avg?: Prisma.CatalogAvgOrderByAggregateInput
  _max?: Prisma.CatalogMaxOrderByAggregateInput
  _min?: Prisma.CatalogMinOrderByAggregateInput
  _sum?: Prisma.CatalogSumOrderByAggregateInput
}

export type CatalogScalarWhereWithAggregatesInput = {
  AND?: Prisma.CatalogScalarWhereWithAggregatesInput | Prisma.CatalogScalarWhereWithAggregatesInput[]
  OR?: Prisma.CatalogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CatalogScalarWhereWithAggregatesInput | Prisma.CatalogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Catalog"> | string
  title?: Prisma.StringWithAggregatesFilter<"Catalog"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Catalog"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Catalog"> | string | null
  year?: Prisma.IntWithAggregatesFilter<"Catalog"> | number
  coverImage?: Prisma.StringNullableWithAggregatesFilter<"Catalog"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"Catalog"> | boolean
  isFeatured?: Prisma.BoolWithAggregatesFilter<"Catalog"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Catalog"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Catalog"> | Date | string
}

export type CatalogCreateInput = {
  id?: string
  title: string
  slug: string
  description?: string | null
  year: number
  coverImage?: string | null
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  pages?: Prisma.CatalogPageCreateNestedManyWithoutCatalogInput
}

export type CatalogUncheckedCreateInput = {
  id?: string
  title: string
  slug: string
  description?: string | null
  year: number
  coverImage?: string | null
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  pages?: Prisma.CatalogPageUncheckedCreateNestedManyWithoutCatalogInput
}

export type CatalogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pages?: Prisma.CatalogPageUpdateManyWithoutCatalogNestedInput
}

export type CatalogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pages?: Prisma.CatalogPageUncheckedUpdateManyWithoutCatalogNestedInput
}

export type CatalogCreateManyInput = {
  id?: string
  title: string
  slug: string
  description?: string | null
  year: number
  coverImage?: string | null
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatalogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogOrderByRelevanceInput = {
  fields: Prisma.CatalogOrderByRelevanceFieldEnum | Prisma.CatalogOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CatalogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  year?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CatalogAvgOrderByAggregateInput = {
  year?: Prisma.SortOrder
}

export type CatalogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  year?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CatalogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  year?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CatalogSumOrderByAggregateInput = {
  year?: Prisma.SortOrder
}

export type CatalogScalarRelationFilter = {
  is?: Prisma.CatalogWhereInput
  isNot?: Prisma.CatalogWhereInput
}

export type CatalogCreateNestedOneWithoutPagesInput = {
  create?: Prisma.XOR<Prisma.CatalogCreateWithoutPagesInput, Prisma.CatalogUncheckedCreateWithoutPagesInput>
  connectOrCreate?: Prisma.CatalogCreateOrConnectWithoutPagesInput
  connect?: Prisma.CatalogWhereUniqueInput
}

export type CatalogUpdateOneRequiredWithoutPagesNestedInput = {
  create?: Prisma.XOR<Prisma.CatalogCreateWithoutPagesInput, Prisma.CatalogUncheckedCreateWithoutPagesInput>
  connectOrCreate?: Prisma.CatalogCreateOrConnectWithoutPagesInput
  upsert?: Prisma.CatalogUpsertWithoutPagesInput
  connect?: Prisma.CatalogWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CatalogUpdateToOneWithWhereWithoutPagesInput, Prisma.CatalogUpdateWithoutPagesInput>, Prisma.CatalogUncheckedUpdateWithoutPagesInput>
}

export type CatalogCreateWithoutPagesInput = {
  id?: string
  title: string
  slug: string
  description?: string | null
  year: number
  coverImage?: string | null
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatalogUncheckedCreateWithoutPagesInput = {
  id?: string
  title: string
  slug: string
  description?: string | null
  year: number
  coverImage?: string | null
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CatalogCreateOrConnectWithoutPagesInput = {
  where: Prisma.CatalogWhereUniqueInput
  create: Prisma.XOR<Prisma.CatalogCreateWithoutPagesInput, Prisma.CatalogUncheckedCreateWithoutPagesInput>
}

export type CatalogUpsertWithoutPagesInput = {
  update: Prisma.XOR<Prisma.CatalogUpdateWithoutPagesInput, Prisma.CatalogUncheckedUpdateWithoutPagesInput>
  create: Prisma.XOR<Prisma.CatalogCreateWithoutPagesInput, Prisma.CatalogUncheckedCreateWithoutPagesInput>
  where?: Prisma.CatalogWhereInput
}

export type CatalogUpdateToOneWithWhereWithoutPagesInput = {
  where?: Prisma.CatalogWhereInput
  data: Prisma.XOR<Prisma.CatalogUpdateWithoutPagesInput, Prisma.CatalogUncheckedUpdateWithoutPagesInput>
}

export type CatalogUpdateWithoutPagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CatalogUncheckedUpdateWithoutPagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CatalogCountOutputType
 */

export type CatalogCountOutputType = {
  pages: number
}

export type CatalogCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pages?: boolean | CatalogCountOutputTypeCountPagesArgs
}

/**
 * CatalogCountOutputType without action
 */
export type CatalogCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogCountOutputType
   */
  select?: Prisma.CatalogCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CatalogCountOutputType without action
 */
export type CatalogCountOutputTypeCountPagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CatalogPageWhereInput
}


export type CatalogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  slug?: boolean
  description?: boolean
  year?: boolean
  coverImage?: boolean
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pages?: boolean | Prisma.Catalog$pagesArgs<ExtArgs>
  _count?: boolean | Prisma.CatalogCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["catalog"]>



export type CatalogSelectScalar = {
  id?: boolean
  title?: boolean
  slug?: boolean
  description?: boolean
  year?: boolean
  coverImage?: boolean
  isActive?: boolean
  isFeatured?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CatalogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "slug" | "description" | "year" | "coverImage" | "isActive" | "isFeatured" | "createdAt" | "updatedAt", ExtArgs["result"]["catalog"]>
export type CatalogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pages?: boolean | Prisma.Catalog$pagesArgs<ExtArgs>
  _count?: boolean | Prisma.CatalogCountOutputTypeDefaultArgs<ExtArgs>
}

export type $CatalogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Catalog"
  objects: {
    pages: Prisma.$CatalogPagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    slug: string
    description: string | null
    year: number
    coverImage: string | null
    isActive: boolean
    isFeatured: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["catalog"]>
  composites: {}
}

export type CatalogGetPayload<S extends boolean | null | undefined | CatalogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CatalogPayload, S>

export type CatalogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CatalogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CatalogCountAggregateInputType | true
  }

export interface CatalogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Catalog'], meta: { name: 'Catalog' } }
  /**
   * Find zero or one Catalog that matches the filter.
   * @param {CatalogFindUniqueArgs} args - Arguments to find a Catalog
   * @example
   * // Get one Catalog
   * const catalog = await prisma.catalog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CatalogFindUniqueArgs>(args: Prisma.SelectSubset<T, CatalogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Catalog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CatalogFindUniqueOrThrowArgs} args - Arguments to find a Catalog
   * @example
   * // Get one Catalog
   * const catalog = await prisma.catalog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CatalogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CatalogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Catalog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogFindFirstArgs} args - Arguments to find a Catalog
   * @example
   * // Get one Catalog
   * const catalog = await prisma.catalog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CatalogFindFirstArgs>(args?: Prisma.SelectSubset<T, CatalogFindFirstArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Catalog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogFindFirstOrThrowArgs} args - Arguments to find a Catalog
   * @example
   * // Get one Catalog
   * const catalog = await prisma.catalog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CatalogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CatalogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Catalogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Catalogs
   * const catalogs = await prisma.catalog.findMany()
   * 
   * // Get first 10 Catalogs
   * const catalogs = await prisma.catalog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const catalogWithIdOnly = await prisma.catalog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CatalogFindManyArgs>(args?: Prisma.SelectSubset<T, CatalogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Catalog.
   * @param {CatalogCreateArgs} args - Arguments to create a Catalog.
   * @example
   * // Create one Catalog
   * const Catalog = await prisma.catalog.create({
   *   data: {
   *     // ... data to create a Catalog
   *   }
   * })
   * 
   */
  create<T extends CatalogCreateArgs>(args: Prisma.SelectSubset<T, CatalogCreateArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Catalogs.
   * @param {CatalogCreateManyArgs} args - Arguments to create many Catalogs.
   * @example
   * // Create many Catalogs
   * const catalog = await prisma.catalog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CatalogCreateManyArgs>(args?: Prisma.SelectSubset<T, CatalogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Catalog.
   * @param {CatalogDeleteArgs} args - Arguments to delete one Catalog.
   * @example
   * // Delete one Catalog
   * const Catalog = await prisma.catalog.delete({
   *   where: {
   *     // ... filter to delete one Catalog
   *   }
   * })
   * 
   */
  delete<T extends CatalogDeleteArgs>(args: Prisma.SelectSubset<T, CatalogDeleteArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Catalog.
   * @param {CatalogUpdateArgs} args - Arguments to update one Catalog.
   * @example
   * // Update one Catalog
   * const catalog = await prisma.catalog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CatalogUpdateArgs>(args: Prisma.SelectSubset<T, CatalogUpdateArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Catalogs.
   * @param {CatalogDeleteManyArgs} args - Arguments to filter Catalogs to delete.
   * @example
   * // Delete a few Catalogs
   * const { count } = await prisma.catalog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CatalogDeleteManyArgs>(args?: Prisma.SelectSubset<T, CatalogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Catalogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Catalogs
   * const catalog = await prisma.catalog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CatalogUpdateManyArgs>(args: Prisma.SelectSubset<T, CatalogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Catalog.
   * @param {CatalogUpsertArgs} args - Arguments to update or create a Catalog.
   * @example
   * // Update or create a Catalog
   * const catalog = await prisma.catalog.upsert({
   *   create: {
   *     // ... data to create a Catalog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Catalog we want to update
   *   }
   * })
   */
  upsert<T extends CatalogUpsertArgs>(args: Prisma.SelectSubset<T, CatalogUpsertArgs<ExtArgs>>): Prisma.Prisma__CatalogClient<runtime.Types.Result.GetResult<Prisma.$CatalogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Catalogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogCountArgs} args - Arguments to filter Catalogs to count.
   * @example
   * // Count the number of Catalogs
   * const count = await prisma.catalog.count({
   *   where: {
   *     // ... the filter for the Catalogs we want to count
   *   }
   * })
  **/
  count<T extends CatalogCountArgs>(
    args?: Prisma.Subset<T, CatalogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CatalogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Catalog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CatalogAggregateArgs>(args: Prisma.Subset<T, CatalogAggregateArgs>): Prisma.PrismaPromise<GetCatalogAggregateType<T>>

  /**
   * Group by Catalog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CatalogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CatalogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CatalogGroupByArgs['orderBy'] }
      : { orderBy?: CatalogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CatalogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCatalogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Catalog model
 */
readonly fields: CatalogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Catalog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CatalogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pages<T extends Prisma.Catalog$pagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Catalog$pagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CatalogPagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Catalog model
 */
export interface CatalogFieldRefs {
  readonly id: Prisma.FieldRef<"Catalog", 'String'>
  readonly title: Prisma.FieldRef<"Catalog", 'String'>
  readonly slug: Prisma.FieldRef<"Catalog", 'String'>
  readonly description: Prisma.FieldRef<"Catalog", 'String'>
  readonly year: Prisma.FieldRef<"Catalog", 'Int'>
  readonly coverImage: Prisma.FieldRef<"Catalog", 'String'>
  readonly isActive: Prisma.FieldRef<"Catalog", 'Boolean'>
  readonly isFeatured: Prisma.FieldRef<"Catalog", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Catalog", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Catalog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Catalog findUnique
 */
export type CatalogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * Filter, which Catalog to fetch.
   */
  where: Prisma.CatalogWhereUniqueInput
}

/**
 * Catalog findUniqueOrThrow
 */
export type CatalogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * Filter, which Catalog to fetch.
   */
  where: Prisma.CatalogWhereUniqueInput
}

/**
 * Catalog findFirst
 */
export type CatalogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * Filter, which Catalog to fetch.
   */
  where?: Prisma.CatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Catalogs to fetch.
   */
  orderBy?: Prisma.CatalogOrderByWithRelationInput | Prisma.CatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Catalogs.
   */
  cursor?: Prisma.CatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Catalogs.
   */
  distinct?: Prisma.CatalogScalarFieldEnum | Prisma.CatalogScalarFieldEnum[]
}

/**
 * Catalog findFirstOrThrow
 */
export type CatalogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * Filter, which Catalog to fetch.
   */
  where?: Prisma.CatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Catalogs to fetch.
   */
  orderBy?: Prisma.CatalogOrderByWithRelationInput | Prisma.CatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Catalogs.
   */
  cursor?: Prisma.CatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Catalogs.
   */
  distinct?: Prisma.CatalogScalarFieldEnum | Prisma.CatalogScalarFieldEnum[]
}

/**
 * Catalog findMany
 */
export type CatalogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * Filter, which Catalogs to fetch.
   */
  where?: Prisma.CatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Catalogs to fetch.
   */
  orderBy?: Prisma.CatalogOrderByWithRelationInput | Prisma.CatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Catalogs.
   */
  cursor?: Prisma.CatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Catalogs.
   */
  skip?: number
  distinct?: Prisma.CatalogScalarFieldEnum | Prisma.CatalogScalarFieldEnum[]
}

/**
 * Catalog create
 */
export type CatalogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * The data needed to create a Catalog.
   */
  data: Prisma.XOR<Prisma.CatalogCreateInput, Prisma.CatalogUncheckedCreateInput>
}

/**
 * Catalog createMany
 */
export type CatalogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Catalogs.
   */
  data: Prisma.CatalogCreateManyInput | Prisma.CatalogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Catalog update
 */
export type CatalogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * The data needed to update a Catalog.
   */
  data: Prisma.XOR<Prisma.CatalogUpdateInput, Prisma.CatalogUncheckedUpdateInput>
  /**
   * Choose, which Catalog to update.
   */
  where: Prisma.CatalogWhereUniqueInput
}

/**
 * Catalog updateMany
 */
export type CatalogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Catalogs.
   */
  data: Prisma.XOR<Prisma.CatalogUpdateManyMutationInput, Prisma.CatalogUncheckedUpdateManyInput>
  /**
   * Filter which Catalogs to update
   */
  where?: Prisma.CatalogWhereInput
  /**
   * Limit how many Catalogs to update.
   */
  limit?: number
}

/**
 * Catalog upsert
 */
export type CatalogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * The filter to search for the Catalog to update in case it exists.
   */
  where: Prisma.CatalogWhereUniqueInput
  /**
   * In case the Catalog found by the `where` argument doesn't exist, create a new Catalog with this data.
   */
  create: Prisma.XOR<Prisma.CatalogCreateInput, Prisma.CatalogUncheckedCreateInput>
  /**
   * In case the Catalog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CatalogUpdateInput, Prisma.CatalogUncheckedUpdateInput>
}

/**
 * Catalog delete
 */
export type CatalogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
  /**
   * Filter which Catalog to delete.
   */
  where: Prisma.CatalogWhereUniqueInput
}

/**
 * Catalog deleteMany
 */
export type CatalogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Catalogs to delete
   */
  where?: Prisma.CatalogWhereInput
  /**
   * Limit how many Catalogs to delete.
   */
  limit?: number
}

/**
 * Catalog.pages
 */
export type Catalog$pagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CatalogPage
   */
  select?: Prisma.CatalogPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CatalogPage
   */
  omit?: Prisma.CatalogPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogPageInclude<ExtArgs> | null
  where?: Prisma.CatalogPageWhereInput
  orderBy?: Prisma.CatalogPageOrderByWithRelationInput | Prisma.CatalogPageOrderByWithRelationInput[]
  cursor?: Prisma.CatalogPageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CatalogPageScalarFieldEnum | Prisma.CatalogPageScalarFieldEnum[]
}

/**
 * Catalog without action
 */
export type CatalogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Catalog
   */
  select?: Prisma.CatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Catalog
   */
  omit?: Prisma.CatalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CatalogInclude<ExtArgs> | null
}
