
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NewsToTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NewsToTag
 * 
 */
export type NewsToTagModel = runtime.Types.Result.DefaultSelection<Prisma.$NewsToTagPayload>

export type AggregateNewsToTag = {
  _count: NewsToTagCountAggregateOutputType | null
  _min: NewsToTagMinAggregateOutputType | null
  _max: NewsToTagMaxAggregateOutputType | null
}

export type NewsToTagMinAggregateOutputType = {
  newsId: string | null
  tagId: string | null
}

export type NewsToTagMaxAggregateOutputType = {
  newsId: string | null
  tagId: string | null
}

export type NewsToTagCountAggregateOutputType = {
  newsId: number
  tagId: number
  _all: number
}


export type NewsToTagMinAggregateInputType = {
  newsId?: true
  tagId?: true
}

export type NewsToTagMaxAggregateInputType = {
  newsId?: true
  tagId?: true
}

export type NewsToTagCountAggregateInputType = {
  newsId?: true
  tagId?: true
  _all?: true
}

export type NewsToTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsToTag to aggregate.
   */
  where?: Prisma.NewsToTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsToTags to fetch.
   */
  orderBy?: Prisma.NewsToTagOrderByWithRelationInput | Prisma.NewsToTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NewsToTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsToTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsToTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NewsToTags
  **/
  _count?: true | NewsToTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NewsToTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NewsToTagMaxAggregateInputType
}

export type GetNewsToTagAggregateType<T extends NewsToTagAggregateArgs> = {
      [P in keyof T & keyof AggregateNewsToTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNewsToTag[P]>
    : Prisma.GetScalarType<T[P], AggregateNewsToTag[P]>
}




export type NewsToTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewsToTagWhereInput
  orderBy?: Prisma.NewsToTagOrderByWithAggregationInput | Prisma.NewsToTagOrderByWithAggregationInput[]
  by: Prisma.NewsToTagScalarFieldEnum[] | Prisma.NewsToTagScalarFieldEnum
  having?: Prisma.NewsToTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NewsToTagCountAggregateInputType | true
  _min?: NewsToTagMinAggregateInputType
  _max?: NewsToTagMaxAggregateInputType
}

export type NewsToTagGroupByOutputType = {
  newsId: string
  tagId: string
  _count: NewsToTagCountAggregateOutputType | null
  _min: NewsToTagMinAggregateOutputType | null
  _max: NewsToTagMaxAggregateOutputType | null
}

type GetNewsToTagGroupByPayload<T extends NewsToTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NewsToTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NewsToTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NewsToTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NewsToTagGroupByOutputType[P]>
      }
    >
  >



export type NewsToTagWhereInput = {
  AND?: Prisma.NewsToTagWhereInput | Prisma.NewsToTagWhereInput[]
  OR?: Prisma.NewsToTagWhereInput[]
  NOT?: Prisma.NewsToTagWhereInput | Prisma.NewsToTagWhereInput[]
  newsId?: Prisma.StringFilter<"NewsToTag"> | string
  tagId?: Prisma.StringFilter<"NewsToTag"> | string
  news?: Prisma.XOR<Prisma.NewsScalarRelationFilter, Prisma.NewsWhereInput>
  tag?: Prisma.XOR<Prisma.NewsTagScalarRelationFilter, Prisma.NewsTagWhereInput>
}

export type NewsToTagOrderByWithRelationInput = {
  newsId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  news?: Prisma.NewsOrderByWithRelationInput
  tag?: Prisma.NewsTagOrderByWithRelationInput
  _relevance?: Prisma.NewsToTagOrderByRelevanceInput
}

export type NewsToTagWhereUniqueInput = Prisma.AtLeast<{
  newsId_tagId?: Prisma.NewsToTagNewsIdTagIdCompoundUniqueInput
  AND?: Prisma.NewsToTagWhereInput | Prisma.NewsToTagWhereInput[]
  OR?: Prisma.NewsToTagWhereInput[]
  NOT?: Prisma.NewsToTagWhereInput | Prisma.NewsToTagWhereInput[]
  newsId?: Prisma.StringFilter<"NewsToTag"> | string
  tagId?: Prisma.StringFilter<"NewsToTag"> | string
  news?: Prisma.XOR<Prisma.NewsScalarRelationFilter, Prisma.NewsWhereInput>
  tag?: Prisma.XOR<Prisma.NewsTagScalarRelationFilter, Prisma.NewsTagWhereInput>
}, "newsId_tagId">

export type NewsToTagOrderByWithAggregationInput = {
  newsId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  _count?: Prisma.NewsToTagCountOrderByAggregateInput
  _max?: Prisma.NewsToTagMaxOrderByAggregateInput
  _min?: Prisma.NewsToTagMinOrderByAggregateInput
}

export type NewsToTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.NewsToTagScalarWhereWithAggregatesInput | Prisma.NewsToTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.NewsToTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NewsToTagScalarWhereWithAggregatesInput | Prisma.NewsToTagScalarWhereWithAggregatesInput[]
  newsId?: Prisma.StringWithAggregatesFilter<"NewsToTag"> | string
  tagId?: Prisma.StringWithAggregatesFilter<"NewsToTag"> | string
}

export type NewsToTagCreateInput = {
  news: Prisma.NewsCreateNestedOneWithoutTagsInput
  tag: Prisma.NewsTagCreateNestedOneWithoutNewsInput
}

export type NewsToTagUncheckedCreateInput = {
  newsId: string
  tagId: string
}

export type NewsToTagUpdateInput = {
  news?: Prisma.NewsUpdateOneRequiredWithoutTagsNestedInput
  tag?: Prisma.NewsTagUpdateOneRequiredWithoutNewsNestedInput
}

export type NewsToTagUncheckedUpdateInput = {
  newsId?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsToTagCreateManyInput = {
  newsId: string
  tagId: string
}

export type NewsToTagUpdateManyMutationInput = {

}

export type NewsToTagUncheckedUpdateManyInput = {
  newsId?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsToTagListRelationFilter = {
  every?: Prisma.NewsToTagWhereInput
  some?: Prisma.NewsToTagWhereInput
  none?: Prisma.NewsToTagWhereInput
}

export type NewsToTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NewsToTagOrderByRelevanceInput = {
  fields: Prisma.NewsToTagOrderByRelevanceFieldEnum | Prisma.NewsToTagOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type NewsToTagNewsIdTagIdCompoundUniqueInput = {
  newsId: string
  tagId: string
}

export type NewsToTagCountOrderByAggregateInput = {
  newsId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type NewsToTagMaxOrderByAggregateInput = {
  newsId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type NewsToTagMinOrderByAggregateInput = {
  newsId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type NewsToTagCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutTagInput, Prisma.NewsToTagUncheckedCreateWithoutTagInput> | Prisma.NewsToTagCreateWithoutTagInput[] | Prisma.NewsToTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutTagInput | Prisma.NewsToTagCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.NewsToTagCreateManyTagInputEnvelope
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
}

export type NewsToTagUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutTagInput, Prisma.NewsToTagUncheckedCreateWithoutTagInput> | Prisma.NewsToTagCreateWithoutTagInput[] | Prisma.NewsToTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutTagInput | Prisma.NewsToTagCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.NewsToTagCreateManyTagInputEnvelope
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
}

export type NewsToTagUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutTagInput, Prisma.NewsToTagUncheckedCreateWithoutTagInput> | Prisma.NewsToTagCreateWithoutTagInput[] | Prisma.NewsToTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutTagInput | Prisma.NewsToTagCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.NewsToTagUpsertWithWhereUniqueWithoutTagInput | Prisma.NewsToTagUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.NewsToTagCreateManyTagInputEnvelope
  set?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  disconnect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  delete?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  update?: Prisma.NewsToTagUpdateWithWhereUniqueWithoutTagInput | Prisma.NewsToTagUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.NewsToTagUpdateManyWithWhereWithoutTagInput | Prisma.NewsToTagUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.NewsToTagScalarWhereInput | Prisma.NewsToTagScalarWhereInput[]
}

export type NewsToTagUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutTagInput, Prisma.NewsToTagUncheckedCreateWithoutTagInput> | Prisma.NewsToTagCreateWithoutTagInput[] | Prisma.NewsToTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutTagInput | Prisma.NewsToTagCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.NewsToTagUpsertWithWhereUniqueWithoutTagInput | Prisma.NewsToTagUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.NewsToTagCreateManyTagInputEnvelope
  set?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  disconnect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  delete?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  update?: Prisma.NewsToTagUpdateWithWhereUniqueWithoutTagInput | Prisma.NewsToTagUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.NewsToTagUpdateManyWithWhereWithoutTagInput | Prisma.NewsToTagUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.NewsToTagScalarWhereInput | Prisma.NewsToTagScalarWhereInput[]
}

export type NewsToTagCreateNestedManyWithoutNewsInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutNewsInput, Prisma.NewsToTagUncheckedCreateWithoutNewsInput> | Prisma.NewsToTagCreateWithoutNewsInput[] | Prisma.NewsToTagUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutNewsInput | Prisma.NewsToTagCreateOrConnectWithoutNewsInput[]
  createMany?: Prisma.NewsToTagCreateManyNewsInputEnvelope
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
}

export type NewsToTagUncheckedCreateNestedManyWithoutNewsInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutNewsInput, Prisma.NewsToTagUncheckedCreateWithoutNewsInput> | Prisma.NewsToTagCreateWithoutNewsInput[] | Prisma.NewsToTagUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutNewsInput | Prisma.NewsToTagCreateOrConnectWithoutNewsInput[]
  createMany?: Prisma.NewsToTagCreateManyNewsInputEnvelope
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
}

export type NewsToTagUpdateManyWithoutNewsNestedInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutNewsInput, Prisma.NewsToTagUncheckedCreateWithoutNewsInput> | Prisma.NewsToTagCreateWithoutNewsInput[] | Prisma.NewsToTagUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutNewsInput | Prisma.NewsToTagCreateOrConnectWithoutNewsInput[]
  upsert?: Prisma.NewsToTagUpsertWithWhereUniqueWithoutNewsInput | Prisma.NewsToTagUpsertWithWhereUniqueWithoutNewsInput[]
  createMany?: Prisma.NewsToTagCreateManyNewsInputEnvelope
  set?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  disconnect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  delete?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  update?: Prisma.NewsToTagUpdateWithWhereUniqueWithoutNewsInput | Prisma.NewsToTagUpdateWithWhereUniqueWithoutNewsInput[]
  updateMany?: Prisma.NewsToTagUpdateManyWithWhereWithoutNewsInput | Prisma.NewsToTagUpdateManyWithWhereWithoutNewsInput[]
  deleteMany?: Prisma.NewsToTagScalarWhereInput | Prisma.NewsToTagScalarWhereInput[]
}

export type NewsToTagUncheckedUpdateManyWithoutNewsNestedInput = {
  create?: Prisma.XOR<Prisma.NewsToTagCreateWithoutNewsInput, Prisma.NewsToTagUncheckedCreateWithoutNewsInput> | Prisma.NewsToTagCreateWithoutNewsInput[] | Prisma.NewsToTagUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsToTagCreateOrConnectWithoutNewsInput | Prisma.NewsToTagCreateOrConnectWithoutNewsInput[]
  upsert?: Prisma.NewsToTagUpsertWithWhereUniqueWithoutNewsInput | Prisma.NewsToTagUpsertWithWhereUniqueWithoutNewsInput[]
  createMany?: Prisma.NewsToTagCreateManyNewsInputEnvelope
  set?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  disconnect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  delete?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  connect?: Prisma.NewsToTagWhereUniqueInput | Prisma.NewsToTagWhereUniqueInput[]
  update?: Prisma.NewsToTagUpdateWithWhereUniqueWithoutNewsInput | Prisma.NewsToTagUpdateWithWhereUniqueWithoutNewsInput[]
  updateMany?: Prisma.NewsToTagUpdateManyWithWhereWithoutNewsInput | Prisma.NewsToTagUpdateManyWithWhereWithoutNewsInput[]
  deleteMany?: Prisma.NewsToTagScalarWhereInput | Prisma.NewsToTagScalarWhereInput[]
}

export type NewsToTagCreateWithoutTagInput = {
  news: Prisma.NewsCreateNestedOneWithoutTagsInput
}

export type NewsToTagUncheckedCreateWithoutTagInput = {
  newsId: string
}

export type NewsToTagCreateOrConnectWithoutTagInput = {
  where: Prisma.NewsToTagWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsToTagCreateWithoutTagInput, Prisma.NewsToTagUncheckedCreateWithoutTagInput>
}

export type NewsToTagCreateManyTagInputEnvelope = {
  data: Prisma.NewsToTagCreateManyTagInput | Prisma.NewsToTagCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type NewsToTagUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.NewsToTagWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsToTagUpdateWithoutTagInput, Prisma.NewsToTagUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.NewsToTagCreateWithoutTagInput, Prisma.NewsToTagUncheckedCreateWithoutTagInput>
}

export type NewsToTagUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.NewsToTagWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsToTagUpdateWithoutTagInput, Prisma.NewsToTagUncheckedUpdateWithoutTagInput>
}

export type NewsToTagUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.NewsToTagScalarWhereInput
  data: Prisma.XOR<Prisma.NewsToTagUpdateManyMutationInput, Prisma.NewsToTagUncheckedUpdateManyWithoutTagInput>
}

export type NewsToTagScalarWhereInput = {
  AND?: Prisma.NewsToTagScalarWhereInput | Prisma.NewsToTagScalarWhereInput[]
  OR?: Prisma.NewsToTagScalarWhereInput[]
  NOT?: Prisma.NewsToTagScalarWhereInput | Prisma.NewsToTagScalarWhereInput[]
  newsId?: Prisma.StringFilter<"NewsToTag"> | string
  tagId?: Prisma.StringFilter<"NewsToTag"> | string
}

export type NewsToTagCreateWithoutNewsInput = {
  tag: Prisma.NewsTagCreateNestedOneWithoutNewsInput
}

export type NewsToTagUncheckedCreateWithoutNewsInput = {
  tagId: string
}

export type NewsToTagCreateOrConnectWithoutNewsInput = {
  where: Prisma.NewsToTagWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsToTagCreateWithoutNewsInput, Prisma.NewsToTagUncheckedCreateWithoutNewsInput>
}

export type NewsToTagCreateManyNewsInputEnvelope = {
  data: Prisma.NewsToTagCreateManyNewsInput | Prisma.NewsToTagCreateManyNewsInput[]
  skipDuplicates?: boolean
}

export type NewsToTagUpsertWithWhereUniqueWithoutNewsInput = {
  where: Prisma.NewsToTagWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsToTagUpdateWithoutNewsInput, Prisma.NewsToTagUncheckedUpdateWithoutNewsInput>
  create: Prisma.XOR<Prisma.NewsToTagCreateWithoutNewsInput, Prisma.NewsToTagUncheckedCreateWithoutNewsInput>
}

export type NewsToTagUpdateWithWhereUniqueWithoutNewsInput = {
  where: Prisma.NewsToTagWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsToTagUpdateWithoutNewsInput, Prisma.NewsToTagUncheckedUpdateWithoutNewsInput>
}

export type NewsToTagUpdateManyWithWhereWithoutNewsInput = {
  where: Prisma.NewsToTagScalarWhereInput
  data: Prisma.XOR<Prisma.NewsToTagUpdateManyMutationInput, Prisma.NewsToTagUncheckedUpdateManyWithoutNewsInput>
}

export type NewsToTagCreateManyTagInput = {
  newsId: string
}

export type NewsToTagUpdateWithoutTagInput = {
  news?: Prisma.NewsUpdateOneRequiredWithoutTagsNestedInput
}

export type NewsToTagUncheckedUpdateWithoutTagInput = {
  newsId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsToTagUncheckedUpdateManyWithoutTagInput = {
  newsId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsToTagCreateManyNewsInput = {
  tagId: string
}

export type NewsToTagUpdateWithoutNewsInput = {
  tag?: Prisma.NewsTagUpdateOneRequiredWithoutNewsNestedInput
}

export type NewsToTagUncheckedUpdateWithoutNewsInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NewsToTagUncheckedUpdateManyWithoutNewsInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type NewsToTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  newsId?: boolean
  tagId?: boolean
  news?: boolean | Prisma.NewsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.NewsTagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsToTag"]>



export type NewsToTagSelectScalar = {
  newsId?: boolean
  tagId?: boolean
}

export type NewsToTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"newsId" | "tagId", ExtArgs["result"]["newsToTag"]>
export type NewsToTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  news?: boolean | Prisma.NewsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.NewsTagDefaultArgs<ExtArgs>
}

export type $NewsToTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NewsToTag"
  objects: {
    news: Prisma.$NewsPayload<ExtArgs>
    tag: Prisma.$NewsTagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    newsId: string
    tagId: string
  }, ExtArgs["result"]["newsToTag"]>
  composites: {}
}

export type NewsToTagGetPayload<S extends boolean | null | undefined | NewsToTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload, S>

export type NewsToTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NewsToTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NewsToTagCountAggregateInputType | true
  }

export interface NewsToTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NewsToTag'], meta: { name: 'NewsToTag' } }
  /**
   * Find zero or one NewsToTag that matches the filter.
   * @param {NewsToTagFindUniqueArgs} args - Arguments to find a NewsToTag
   * @example
   * // Get one NewsToTag
   * const newsToTag = await prisma.newsToTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NewsToTagFindUniqueArgs>(args: Prisma.SelectSubset<T, NewsToTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NewsToTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NewsToTagFindUniqueOrThrowArgs} args - Arguments to find a NewsToTag
   * @example
   * // Get one NewsToTag
   * const newsToTag = await prisma.newsToTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NewsToTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NewsToTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsToTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagFindFirstArgs} args - Arguments to find a NewsToTag
   * @example
   * // Get one NewsToTag
   * const newsToTag = await prisma.newsToTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NewsToTagFindFirstArgs>(args?: Prisma.SelectSubset<T, NewsToTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsToTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagFindFirstOrThrowArgs} args - Arguments to find a NewsToTag
   * @example
   * // Get one NewsToTag
   * const newsToTag = await prisma.newsToTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NewsToTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NewsToTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NewsToTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NewsToTags
   * const newsToTags = await prisma.newsToTag.findMany()
   * 
   * // Get first 10 NewsToTags
   * const newsToTags = await prisma.newsToTag.findMany({ take: 10 })
   * 
   * // Only select the `newsId`
   * const newsToTagWithNewsIdOnly = await prisma.newsToTag.findMany({ select: { newsId: true } })
   * 
   */
  findMany<T extends NewsToTagFindManyArgs>(args?: Prisma.SelectSubset<T, NewsToTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NewsToTag.
   * @param {NewsToTagCreateArgs} args - Arguments to create a NewsToTag.
   * @example
   * // Create one NewsToTag
   * const NewsToTag = await prisma.newsToTag.create({
   *   data: {
   *     // ... data to create a NewsToTag
   *   }
   * })
   * 
   */
  create<T extends NewsToTagCreateArgs>(args: Prisma.SelectSubset<T, NewsToTagCreateArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NewsToTags.
   * @param {NewsToTagCreateManyArgs} args - Arguments to create many NewsToTags.
   * @example
   * // Create many NewsToTags
   * const newsToTag = await prisma.newsToTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NewsToTagCreateManyArgs>(args?: Prisma.SelectSubset<T, NewsToTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a NewsToTag.
   * @param {NewsToTagDeleteArgs} args - Arguments to delete one NewsToTag.
   * @example
   * // Delete one NewsToTag
   * const NewsToTag = await prisma.newsToTag.delete({
   *   where: {
   *     // ... filter to delete one NewsToTag
   *   }
   * })
   * 
   */
  delete<T extends NewsToTagDeleteArgs>(args: Prisma.SelectSubset<T, NewsToTagDeleteArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NewsToTag.
   * @param {NewsToTagUpdateArgs} args - Arguments to update one NewsToTag.
   * @example
   * // Update one NewsToTag
   * const newsToTag = await prisma.newsToTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NewsToTagUpdateArgs>(args: Prisma.SelectSubset<T, NewsToTagUpdateArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NewsToTags.
   * @param {NewsToTagDeleteManyArgs} args - Arguments to filter NewsToTags to delete.
   * @example
   * // Delete a few NewsToTags
   * const { count } = await prisma.newsToTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NewsToTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, NewsToTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsToTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NewsToTags
   * const newsToTag = await prisma.newsToTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NewsToTagUpdateManyArgs>(args: Prisma.SelectSubset<T, NewsToTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one NewsToTag.
   * @param {NewsToTagUpsertArgs} args - Arguments to update or create a NewsToTag.
   * @example
   * // Update or create a NewsToTag
   * const newsToTag = await prisma.newsToTag.upsert({
   *   create: {
   *     // ... data to create a NewsToTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NewsToTag we want to update
   *   }
   * })
   */
  upsert<T extends NewsToTagUpsertArgs>(args: Prisma.SelectSubset<T, NewsToTagUpsertArgs<ExtArgs>>): Prisma.Prisma__NewsToTagClient<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NewsToTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagCountArgs} args - Arguments to filter NewsToTags to count.
   * @example
   * // Count the number of NewsToTags
   * const count = await prisma.newsToTag.count({
   *   where: {
   *     // ... the filter for the NewsToTags we want to count
   *   }
   * })
  **/
  count<T extends NewsToTagCountArgs>(
    args?: Prisma.Subset<T, NewsToTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NewsToTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NewsToTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NewsToTagAggregateArgs>(args: Prisma.Subset<T, NewsToTagAggregateArgs>): Prisma.PrismaPromise<GetNewsToTagAggregateType<T>>

  /**
   * Group by NewsToTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsToTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NewsToTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NewsToTagGroupByArgs['orderBy'] }
      : { orderBy?: NewsToTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NewsToTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNewsToTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NewsToTag model
 */
readonly fields: NewsToTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NewsToTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NewsToTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  news<T extends Prisma.NewsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsDefaultArgs<ExtArgs>>): Prisma.Prisma__NewsClient<runtime.Types.Result.GetResult<Prisma.$NewsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.NewsTagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsTagDefaultArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NewsToTag model
 */
export interface NewsToTagFieldRefs {
  readonly newsId: Prisma.FieldRef<"NewsToTag", 'String'>
  readonly tagId: Prisma.FieldRef<"NewsToTag", 'String'>
}
    

// Custom InputTypes
/**
 * NewsToTag findUnique
 */
export type NewsToTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsToTag to fetch.
   */
  where: Prisma.NewsToTagWhereUniqueInput
}

/**
 * NewsToTag findUniqueOrThrow
 */
export type NewsToTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsToTag to fetch.
   */
  where: Prisma.NewsToTagWhereUniqueInput
}

/**
 * NewsToTag findFirst
 */
export type NewsToTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsToTag to fetch.
   */
  where?: Prisma.NewsToTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsToTags to fetch.
   */
  orderBy?: Prisma.NewsToTagOrderByWithRelationInput | Prisma.NewsToTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsToTags.
   */
  cursor?: Prisma.NewsToTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsToTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsToTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsToTags.
   */
  distinct?: Prisma.NewsToTagScalarFieldEnum | Prisma.NewsToTagScalarFieldEnum[]
}

/**
 * NewsToTag findFirstOrThrow
 */
export type NewsToTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsToTag to fetch.
   */
  where?: Prisma.NewsToTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsToTags to fetch.
   */
  orderBy?: Prisma.NewsToTagOrderByWithRelationInput | Prisma.NewsToTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsToTags.
   */
  cursor?: Prisma.NewsToTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsToTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsToTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsToTags.
   */
  distinct?: Prisma.NewsToTagScalarFieldEnum | Prisma.NewsToTagScalarFieldEnum[]
}

/**
 * NewsToTag findMany
 */
export type NewsToTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsToTags to fetch.
   */
  where?: Prisma.NewsToTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsToTags to fetch.
   */
  orderBy?: Prisma.NewsToTagOrderByWithRelationInput | Prisma.NewsToTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NewsToTags.
   */
  cursor?: Prisma.NewsToTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsToTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsToTags.
   */
  skip?: number
  distinct?: Prisma.NewsToTagScalarFieldEnum | Prisma.NewsToTagScalarFieldEnum[]
}

/**
 * NewsToTag create
 */
export type NewsToTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * The data needed to create a NewsToTag.
   */
  data: Prisma.XOR<Prisma.NewsToTagCreateInput, Prisma.NewsToTagUncheckedCreateInput>
}

/**
 * NewsToTag createMany
 */
export type NewsToTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NewsToTags.
   */
  data: Prisma.NewsToTagCreateManyInput | Prisma.NewsToTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NewsToTag update
 */
export type NewsToTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * The data needed to update a NewsToTag.
   */
  data: Prisma.XOR<Prisma.NewsToTagUpdateInput, Prisma.NewsToTagUncheckedUpdateInput>
  /**
   * Choose, which NewsToTag to update.
   */
  where: Prisma.NewsToTagWhereUniqueInput
}

/**
 * NewsToTag updateMany
 */
export type NewsToTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NewsToTags.
   */
  data: Prisma.XOR<Prisma.NewsToTagUpdateManyMutationInput, Prisma.NewsToTagUncheckedUpdateManyInput>
  /**
   * Filter which NewsToTags to update
   */
  where?: Prisma.NewsToTagWhereInput
  /**
   * Limit how many NewsToTags to update.
   */
  limit?: number
}

/**
 * NewsToTag upsert
 */
export type NewsToTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * The filter to search for the NewsToTag to update in case it exists.
   */
  where: Prisma.NewsToTagWhereUniqueInput
  /**
   * In case the NewsToTag found by the `where` argument doesn't exist, create a new NewsToTag with this data.
   */
  create: Prisma.XOR<Prisma.NewsToTagCreateInput, Prisma.NewsToTagUncheckedCreateInput>
  /**
   * In case the NewsToTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NewsToTagUpdateInput, Prisma.NewsToTagUncheckedUpdateInput>
}

/**
 * NewsToTag delete
 */
export type NewsToTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  /**
   * Filter which NewsToTag to delete.
   */
  where: Prisma.NewsToTagWhereUniqueInput
}

/**
 * NewsToTag deleteMany
 */
export type NewsToTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsToTags to delete
   */
  where?: Prisma.NewsToTagWhereInput
  /**
   * Limit how many NewsToTags to delete.
   */
  limit?: number
}

/**
 * NewsToTag without action
 */
export type NewsToTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
}
