
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NewsImage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NewsImage
 * 
 */
export type NewsImageModel = runtime.Types.Result.DefaultSelection<Prisma.$NewsImagePayload>

export type AggregateNewsImage = {
  _count: NewsImageCountAggregateOutputType | null
  _avg: NewsImageAvgAggregateOutputType | null
  _sum: NewsImageSumAggregateOutputType | null
  _min: NewsImageMinAggregateOutputType | null
  _max: NewsImageMaxAggregateOutputType | null
}

export type NewsImageAvgAggregateOutputType = {
  order: number | null
}

export type NewsImageSumAggregateOutputType = {
  order: number | null
}

export type NewsImageMinAggregateOutputType = {
  id: string | null
  newsId: string | null
  url: string | null
  alt: string | null
  order: number | null
  createdAt: Date | null
}

export type NewsImageMaxAggregateOutputType = {
  id: string | null
  newsId: string | null
  url: string | null
  alt: string | null
  order: number | null
  createdAt: Date | null
}

export type NewsImageCountAggregateOutputType = {
  id: number
  newsId: number
  url: number
  alt: number
  order: number
  createdAt: number
  _all: number
}


export type NewsImageAvgAggregateInputType = {
  order?: true
}

export type NewsImageSumAggregateInputType = {
  order?: true
}

export type NewsImageMinAggregateInputType = {
  id?: true
  newsId?: true
  url?: true
  alt?: true
  order?: true
  createdAt?: true
}

export type NewsImageMaxAggregateInputType = {
  id?: true
  newsId?: true
  url?: true
  alt?: true
  order?: true
  createdAt?: true
}

export type NewsImageCountAggregateInputType = {
  id?: true
  newsId?: true
  url?: true
  alt?: true
  order?: true
  createdAt?: true
  _all?: true
}

export type NewsImageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsImage to aggregate.
   */
  where?: Prisma.NewsImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsImages to fetch.
   */
  orderBy?: Prisma.NewsImageOrderByWithRelationInput | Prisma.NewsImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NewsImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NewsImages
  **/
  _count?: true | NewsImageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NewsImageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NewsImageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NewsImageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NewsImageMaxAggregateInputType
}

export type GetNewsImageAggregateType<T extends NewsImageAggregateArgs> = {
      [P in keyof T & keyof AggregateNewsImage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNewsImage[P]>
    : Prisma.GetScalarType<T[P], AggregateNewsImage[P]>
}




export type NewsImageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewsImageWhereInput
  orderBy?: Prisma.NewsImageOrderByWithAggregationInput | Prisma.NewsImageOrderByWithAggregationInput[]
  by: Prisma.NewsImageScalarFieldEnum[] | Prisma.NewsImageScalarFieldEnum
  having?: Prisma.NewsImageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NewsImageCountAggregateInputType | true
  _avg?: NewsImageAvgAggregateInputType
  _sum?: NewsImageSumAggregateInputType
  _min?: NewsImageMinAggregateInputType
  _max?: NewsImageMaxAggregateInputType
}

export type NewsImageGroupByOutputType = {
  id: string
  newsId: string
  url: string
  alt: string | null
  order: number
  createdAt: Date
  _count: NewsImageCountAggregateOutputType | null
  _avg: NewsImageAvgAggregateOutputType | null
  _sum: NewsImageSumAggregateOutputType | null
  _min: NewsImageMinAggregateOutputType | null
  _max: NewsImageMaxAggregateOutputType | null
}

type GetNewsImageGroupByPayload<T extends NewsImageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NewsImageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NewsImageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NewsImageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NewsImageGroupByOutputType[P]>
      }
    >
  >



export type NewsImageWhereInput = {
  AND?: Prisma.NewsImageWhereInput | Prisma.NewsImageWhereInput[]
  OR?: Prisma.NewsImageWhereInput[]
  NOT?: Prisma.NewsImageWhereInput | Prisma.NewsImageWhereInput[]
  id?: Prisma.StringFilter<"NewsImage"> | string
  newsId?: Prisma.StringFilter<"NewsImage"> | string
  url?: Prisma.StringFilter<"NewsImage"> | string
  alt?: Prisma.StringNullableFilter<"NewsImage"> | string | null
  order?: Prisma.IntFilter<"NewsImage"> | number
  createdAt?: Prisma.DateTimeFilter<"NewsImage"> | Date | string
  news?: Prisma.XOR<Prisma.NewsScalarRelationFilter, Prisma.NewsWhereInput>
}

export type NewsImageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  newsId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  alt?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  news?: Prisma.NewsOrderByWithRelationInput
  _relevance?: Prisma.NewsImageOrderByRelevanceInput
}

export type NewsImageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NewsImageWhereInput | Prisma.NewsImageWhereInput[]
  OR?: Prisma.NewsImageWhereInput[]
  NOT?: Prisma.NewsImageWhereInput | Prisma.NewsImageWhereInput[]
  newsId?: Prisma.StringFilter<"NewsImage"> | string
  url?: Prisma.StringFilter<"NewsImage"> | string
  alt?: Prisma.StringNullableFilter<"NewsImage"> | string | null
  order?: Prisma.IntFilter<"NewsImage"> | number
  createdAt?: Prisma.DateTimeFilter<"NewsImage"> | Date | string
  news?: Prisma.XOR<Prisma.NewsScalarRelationFilter, Prisma.NewsWhereInput>
}, "id">

export type NewsImageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  newsId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  alt?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.NewsImageCountOrderByAggregateInput
  _avg?: Prisma.NewsImageAvgOrderByAggregateInput
  _max?: Prisma.NewsImageMaxOrderByAggregateInput
  _min?: Prisma.NewsImageMinOrderByAggregateInput
  _sum?: Prisma.NewsImageSumOrderByAggregateInput
}

export type NewsImageScalarWhereWithAggregatesInput = {
  AND?: Prisma.NewsImageScalarWhereWithAggregatesInput | Prisma.NewsImageScalarWhereWithAggregatesInput[]
  OR?: Prisma.NewsImageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NewsImageScalarWhereWithAggregatesInput | Prisma.NewsImageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NewsImage"> | string
  newsId?: Prisma.StringWithAggregatesFilter<"NewsImage"> | string
  url?: Prisma.StringWithAggregatesFilter<"NewsImage"> | string
  alt?: Prisma.StringNullableWithAggregatesFilter<"NewsImage"> | string | null
  order?: Prisma.IntWithAggregatesFilter<"NewsImage"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NewsImage"> | Date | string
}

export type NewsImageCreateInput = {
  id?: string
  url: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
  news: Prisma.NewsCreateNestedOneWithoutImagesInput
}

export type NewsImageUncheckedCreateInput = {
  id?: string
  newsId: string
  url: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type NewsImageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  news?: Prisma.NewsUpdateOneRequiredWithoutImagesNestedInput
}

export type NewsImageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  newsId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsImageCreateManyInput = {
  id?: string
  newsId: string
  url: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type NewsImageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsImageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  newsId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsImageListRelationFilter = {
  every?: Prisma.NewsImageWhereInput
  some?: Prisma.NewsImageWhereInput
  none?: Prisma.NewsImageWhereInput
}

export type NewsImageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NewsImageOrderByRelevanceInput = {
  fields: Prisma.NewsImageOrderByRelevanceFieldEnum | Prisma.NewsImageOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type NewsImageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  newsId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  alt?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NewsImageAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type NewsImageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  newsId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  alt?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NewsImageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  newsId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  alt?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NewsImageSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type NewsImageCreateNestedManyWithoutNewsInput = {
  create?: Prisma.XOR<Prisma.NewsImageCreateWithoutNewsInput, Prisma.NewsImageUncheckedCreateWithoutNewsInput> | Prisma.NewsImageCreateWithoutNewsInput[] | Prisma.NewsImageUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsImageCreateOrConnectWithoutNewsInput | Prisma.NewsImageCreateOrConnectWithoutNewsInput[]
  createMany?: Prisma.NewsImageCreateManyNewsInputEnvelope
  connect?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
}

export type NewsImageUncheckedCreateNestedManyWithoutNewsInput = {
  create?: Prisma.XOR<Prisma.NewsImageCreateWithoutNewsInput, Prisma.NewsImageUncheckedCreateWithoutNewsInput> | Prisma.NewsImageCreateWithoutNewsInput[] | Prisma.NewsImageUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsImageCreateOrConnectWithoutNewsInput | Prisma.NewsImageCreateOrConnectWithoutNewsInput[]
  createMany?: Prisma.NewsImageCreateManyNewsInputEnvelope
  connect?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
}

export type NewsImageUpdateManyWithoutNewsNestedInput = {
  create?: Prisma.XOR<Prisma.NewsImageCreateWithoutNewsInput, Prisma.NewsImageUncheckedCreateWithoutNewsInput> | Prisma.NewsImageCreateWithoutNewsInput[] | Prisma.NewsImageUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsImageCreateOrConnectWithoutNewsInput | Prisma.NewsImageCreateOrConnectWithoutNewsInput[]
  upsert?: Prisma.NewsImageUpsertWithWhereUniqueWithoutNewsInput | Prisma.NewsImageUpsertWithWhereUniqueWithoutNewsInput[]
  createMany?: Prisma.NewsImageCreateManyNewsInputEnvelope
  set?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  disconnect?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  delete?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  connect?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  update?: Prisma.NewsImageUpdateWithWhereUniqueWithoutNewsInput | Prisma.NewsImageUpdateWithWhereUniqueWithoutNewsInput[]
  updateMany?: Prisma.NewsImageUpdateManyWithWhereWithoutNewsInput | Prisma.NewsImageUpdateManyWithWhereWithoutNewsInput[]
  deleteMany?: Prisma.NewsImageScalarWhereInput | Prisma.NewsImageScalarWhereInput[]
}

export type NewsImageUncheckedUpdateManyWithoutNewsNestedInput = {
  create?: Prisma.XOR<Prisma.NewsImageCreateWithoutNewsInput, Prisma.NewsImageUncheckedCreateWithoutNewsInput> | Prisma.NewsImageCreateWithoutNewsInput[] | Prisma.NewsImageUncheckedCreateWithoutNewsInput[]
  connectOrCreate?: Prisma.NewsImageCreateOrConnectWithoutNewsInput | Prisma.NewsImageCreateOrConnectWithoutNewsInput[]
  upsert?: Prisma.NewsImageUpsertWithWhereUniqueWithoutNewsInput | Prisma.NewsImageUpsertWithWhereUniqueWithoutNewsInput[]
  createMany?: Prisma.NewsImageCreateManyNewsInputEnvelope
  set?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  disconnect?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  delete?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  connect?: Prisma.NewsImageWhereUniqueInput | Prisma.NewsImageWhereUniqueInput[]
  update?: Prisma.NewsImageUpdateWithWhereUniqueWithoutNewsInput | Prisma.NewsImageUpdateWithWhereUniqueWithoutNewsInput[]
  updateMany?: Prisma.NewsImageUpdateManyWithWhereWithoutNewsInput | Prisma.NewsImageUpdateManyWithWhereWithoutNewsInput[]
  deleteMany?: Prisma.NewsImageScalarWhereInput | Prisma.NewsImageScalarWhereInput[]
}

export type NewsImageCreateWithoutNewsInput = {
  id?: string
  url: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type NewsImageUncheckedCreateWithoutNewsInput = {
  id?: string
  url: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type NewsImageCreateOrConnectWithoutNewsInput = {
  where: Prisma.NewsImageWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsImageCreateWithoutNewsInput, Prisma.NewsImageUncheckedCreateWithoutNewsInput>
}

export type NewsImageCreateManyNewsInputEnvelope = {
  data: Prisma.NewsImageCreateManyNewsInput | Prisma.NewsImageCreateManyNewsInput[]
  skipDuplicates?: boolean
}

export type NewsImageUpsertWithWhereUniqueWithoutNewsInput = {
  where: Prisma.NewsImageWhereUniqueInput
  update: Prisma.XOR<Prisma.NewsImageUpdateWithoutNewsInput, Prisma.NewsImageUncheckedUpdateWithoutNewsInput>
  create: Prisma.XOR<Prisma.NewsImageCreateWithoutNewsInput, Prisma.NewsImageUncheckedCreateWithoutNewsInput>
}

export type NewsImageUpdateWithWhereUniqueWithoutNewsInput = {
  where: Prisma.NewsImageWhereUniqueInput
  data: Prisma.XOR<Prisma.NewsImageUpdateWithoutNewsInput, Prisma.NewsImageUncheckedUpdateWithoutNewsInput>
}

export type NewsImageUpdateManyWithWhereWithoutNewsInput = {
  where: Prisma.NewsImageScalarWhereInput
  data: Prisma.XOR<Prisma.NewsImageUpdateManyMutationInput, Prisma.NewsImageUncheckedUpdateManyWithoutNewsInput>
}

export type NewsImageScalarWhereInput = {
  AND?: Prisma.NewsImageScalarWhereInput | Prisma.NewsImageScalarWhereInput[]
  OR?: Prisma.NewsImageScalarWhereInput[]
  NOT?: Prisma.NewsImageScalarWhereInput | Prisma.NewsImageScalarWhereInput[]
  id?: Prisma.StringFilter<"NewsImage"> | string
  newsId?: Prisma.StringFilter<"NewsImage"> | string
  url?: Prisma.StringFilter<"NewsImage"> | string
  alt?: Prisma.StringNullableFilter<"NewsImage"> | string | null
  order?: Prisma.IntFilter<"NewsImage"> | number
  createdAt?: Prisma.DateTimeFilter<"NewsImage"> | Date | string
}

export type NewsImageCreateManyNewsInput = {
  id?: string
  url: string
  alt?: string | null
  order?: number
  createdAt?: Date | string
}

export type NewsImageUpdateWithoutNewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsImageUncheckedUpdateWithoutNewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsImageUncheckedUpdateManyWithoutNewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  alt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NewsImageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  newsId?: boolean
  url?: boolean
  alt?: boolean
  order?: boolean
  createdAt?: boolean
  news?: boolean | Prisma.NewsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsImage"]>



export type NewsImageSelectScalar = {
  id?: boolean
  newsId?: boolean
  url?: boolean
  alt?: boolean
  order?: boolean
  createdAt?: boolean
}

export type NewsImageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "newsId" | "url" | "alt" | "order" | "createdAt", ExtArgs["result"]["newsImage"]>
export type NewsImageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  news?: boolean | Prisma.NewsDefaultArgs<ExtArgs>
}

export type $NewsImagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NewsImage"
  objects: {
    news: Prisma.$NewsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    newsId: string
    url: string
    alt: string | null
    order: number
    createdAt: Date
  }, ExtArgs["result"]["newsImage"]>
  composites: {}
}

export type NewsImageGetPayload<S extends boolean | null | undefined | NewsImageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NewsImagePayload, S>

export type NewsImageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NewsImageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NewsImageCountAggregateInputType | true
  }

export interface NewsImageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NewsImage'], meta: { name: 'NewsImage' } }
  /**
   * Find zero or one NewsImage that matches the filter.
   * @param {NewsImageFindUniqueArgs} args - Arguments to find a NewsImage
   * @example
   * // Get one NewsImage
   * const newsImage = await prisma.newsImage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NewsImageFindUniqueArgs>(args: Prisma.SelectSubset<T, NewsImageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NewsImage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NewsImageFindUniqueOrThrowArgs} args - Arguments to find a NewsImage
   * @example
   * // Get one NewsImage
   * const newsImage = await prisma.newsImage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NewsImageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NewsImageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsImage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageFindFirstArgs} args - Arguments to find a NewsImage
   * @example
   * // Get one NewsImage
   * const newsImage = await prisma.newsImage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NewsImageFindFirstArgs>(args?: Prisma.SelectSubset<T, NewsImageFindFirstArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsImage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageFindFirstOrThrowArgs} args - Arguments to find a NewsImage
   * @example
   * // Get one NewsImage
   * const newsImage = await prisma.newsImage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NewsImageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NewsImageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NewsImages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NewsImages
   * const newsImages = await prisma.newsImage.findMany()
   * 
   * // Get first 10 NewsImages
   * const newsImages = await prisma.newsImage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const newsImageWithIdOnly = await prisma.newsImage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NewsImageFindManyArgs>(args?: Prisma.SelectSubset<T, NewsImageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NewsImage.
   * @param {NewsImageCreateArgs} args - Arguments to create a NewsImage.
   * @example
   * // Create one NewsImage
   * const NewsImage = await prisma.newsImage.create({
   *   data: {
   *     // ... data to create a NewsImage
   *   }
   * })
   * 
   */
  create<T extends NewsImageCreateArgs>(args: Prisma.SelectSubset<T, NewsImageCreateArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NewsImages.
   * @param {NewsImageCreateManyArgs} args - Arguments to create many NewsImages.
   * @example
   * // Create many NewsImages
   * const newsImage = await prisma.newsImage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NewsImageCreateManyArgs>(args?: Prisma.SelectSubset<T, NewsImageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a NewsImage.
   * @param {NewsImageDeleteArgs} args - Arguments to delete one NewsImage.
   * @example
   * // Delete one NewsImage
   * const NewsImage = await prisma.newsImage.delete({
   *   where: {
   *     // ... filter to delete one NewsImage
   *   }
   * })
   * 
   */
  delete<T extends NewsImageDeleteArgs>(args: Prisma.SelectSubset<T, NewsImageDeleteArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NewsImage.
   * @param {NewsImageUpdateArgs} args - Arguments to update one NewsImage.
   * @example
   * // Update one NewsImage
   * const newsImage = await prisma.newsImage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NewsImageUpdateArgs>(args: Prisma.SelectSubset<T, NewsImageUpdateArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NewsImages.
   * @param {NewsImageDeleteManyArgs} args - Arguments to filter NewsImages to delete.
   * @example
   * // Delete a few NewsImages
   * const { count } = await prisma.newsImage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NewsImageDeleteManyArgs>(args?: Prisma.SelectSubset<T, NewsImageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NewsImages
   * const newsImage = await prisma.newsImage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NewsImageUpdateManyArgs>(args: Prisma.SelectSubset<T, NewsImageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one NewsImage.
   * @param {NewsImageUpsertArgs} args - Arguments to update or create a NewsImage.
   * @example
   * // Update or create a NewsImage
   * const newsImage = await prisma.newsImage.upsert({
   *   create: {
   *     // ... data to create a NewsImage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NewsImage we want to update
   *   }
   * })
   */
  upsert<T extends NewsImageUpsertArgs>(args: Prisma.SelectSubset<T, NewsImageUpsertArgs<ExtArgs>>): Prisma.Prisma__NewsImageClient<runtime.Types.Result.GetResult<Prisma.$NewsImagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NewsImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageCountArgs} args - Arguments to filter NewsImages to count.
   * @example
   * // Count the number of NewsImages
   * const count = await prisma.newsImage.count({
   *   where: {
   *     // ... the filter for the NewsImages we want to count
   *   }
   * })
  **/
  count<T extends NewsImageCountArgs>(
    args?: Prisma.Subset<T, NewsImageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NewsImageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NewsImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NewsImageAggregateArgs>(args: Prisma.Subset<T, NewsImageAggregateArgs>): Prisma.PrismaPromise<GetNewsImageAggregateType<T>>

  /**
   * Group by NewsImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsImageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NewsImageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NewsImageGroupByArgs['orderBy'] }
      : { orderBy?: NewsImageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NewsImageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNewsImageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NewsImage model
 */
readonly fields: NewsImageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NewsImage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NewsImageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  news<T extends Prisma.NewsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsDefaultArgs<ExtArgs>>): Prisma.Prisma__NewsClient<runtime.Types.Result.GetResult<Prisma.$NewsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NewsImage model
 */
export interface NewsImageFieldRefs {
  readonly id: Prisma.FieldRef<"NewsImage", 'String'>
  readonly newsId: Prisma.FieldRef<"NewsImage", 'String'>
  readonly url: Prisma.FieldRef<"NewsImage", 'String'>
  readonly alt: Prisma.FieldRef<"NewsImage", 'String'>
  readonly order: Prisma.FieldRef<"NewsImage", 'Int'>
  readonly createdAt: Prisma.FieldRef<"NewsImage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NewsImage findUnique
 */
export type NewsImageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * Filter, which NewsImage to fetch.
   */
  where: Prisma.NewsImageWhereUniqueInput
}

/**
 * NewsImage findUniqueOrThrow
 */
export type NewsImageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * Filter, which NewsImage to fetch.
   */
  where: Prisma.NewsImageWhereUniqueInput
}

/**
 * NewsImage findFirst
 */
export type NewsImageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * Filter, which NewsImage to fetch.
   */
  where?: Prisma.NewsImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsImages to fetch.
   */
  orderBy?: Prisma.NewsImageOrderByWithRelationInput | Prisma.NewsImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsImages.
   */
  cursor?: Prisma.NewsImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsImages.
   */
  distinct?: Prisma.NewsImageScalarFieldEnum | Prisma.NewsImageScalarFieldEnum[]
}

/**
 * NewsImage findFirstOrThrow
 */
export type NewsImageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * Filter, which NewsImage to fetch.
   */
  where?: Prisma.NewsImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsImages to fetch.
   */
  orderBy?: Prisma.NewsImageOrderByWithRelationInput | Prisma.NewsImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsImages.
   */
  cursor?: Prisma.NewsImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsImages.
   */
  distinct?: Prisma.NewsImageScalarFieldEnum | Prisma.NewsImageScalarFieldEnum[]
}

/**
 * NewsImage findMany
 */
export type NewsImageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * Filter, which NewsImages to fetch.
   */
  where?: Prisma.NewsImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsImages to fetch.
   */
  orderBy?: Prisma.NewsImageOrderByWithRelationInput | Prisma.NewsImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NewsImages.
   */
  cursor?: Prisma.NewsImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsImages.
   */
  skip?: number
  distinct?: Prisma.NewsImageScalarFieldEnum | Prisma.NewsImageScalarFieldEnum[]
}

/**
 * NewsImage create
 */
export type NewsImageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * The data needed to create a NewsImage.
   */
  data: Prisma.XOR<Prisma.NewsImageCreateInput, Prisma.NewsImageUncheckedCreateInput>
}

/**
 * NewsImage createMany
 */
export type NewsImageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NewsImages.
   */
  data: Prisma.NewsImageCreateManyInput | Prisma.NewsImageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NewsImage update
 */
export type NewsImageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * The data needed to update a NewsImage.
   */
  data: Prisma.XOR<Prisma.NewsImageUpdateInput, Prisma.NewsImageUncheckedUpdateInput>
  /**
   * Choose, which NewsImage to update.
   */
  where: Prisma.NewsImageWhereUniqueInput
}

/**
 * NewsImage updateMany
 */
export type NewsImageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NewsImages.
   */
  data: Prisma.XOR<Prisma.NewsImageUpdateManyMutationInput, Prisma.NewsImageUncheckedUpdateManyInput>
  /**
   * Filter which NewsImages to update
   */
  where?: Prisma.NewsImageWhereInput
  /**
   * Limit how many NewsImages to update.
   */
  limit?: number
}

/**
 * NewsImage upsert
 */
export type NewsImageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * The filter to search for the NewsImage to update in case it exists.
   */
  where: Prisma.NewsImageWhereUniqueInput
  /**
   * In case the NewsImage found by the `where` argument doesn't exist, create a new NewsImage with this data.
   */
  create: Prisma.XOR<Prisma.NewsImageCreateInput, Prisma.NewsImageUncheckedCreateInput>
  /**
   * In case the NewsImage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NewsImageUpdateInput, Prisma.NewsImageUncheckedUpdateInput>
}

/**
 * NewsImage delete
 */
export type NewsImageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
  /**
   * Filter which NewsImage to delete.
   */
  where: Prisma.NewsImageWhereUniqueInput
}

/**
 * NewsImage deleteMany
 */
export type NewsImageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsImages to delete
   */
  where?: Prisma.NewsImageWhereInput
  /**
   * Limit how many NewsImages to delete.
   */
  limit?: number
}

/**
 * NewsImage without action
 */
export type NewsImageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsImage
   */
  select?: Prisma.NewsImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsImage
   */
  omit?: Prisma.NewsImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsImageInclude<ExtArgs> | null
}
