
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NewsTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NewsTag
 * 
 */
export type NewsTagModel = runtime.Types.Result.DefaultSelection<Prisma.$NewsTagPayload>

export type AggregateNewsTag = {
  _count: NewsTagCountAggregateOutputType | null
  _avg: NewsTagAvgAggregateOutputType | null
  _sum: NewsTagSumAggregateOutputType | null
  _min: NewsTagMinAggregateOutputType | null
  _max: NewsTagMaxAggregateOutputType | null
}

export type NewsTagAvgAggregateOutputType = {
  order: number | null
}

export type NewsTagSumAggregateOutputType = {
  order: number | null
}

export type NewsTagMinAggregateOutputType = {
  id: string | null
  order: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NewsTagMaxAggregateOutputType = {
  id: string | null
  order: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NewsTagCountAggregateOutputType = {
  id: number
  order: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NewsTagAvgAggregateInputType = {
  order?: true
}

export type NewsTagSumAggregateInputType = {
  order?: true
}

export type NewsTagMinAggregateInputType = {
  id?: true
  order?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type NewsTagMaxAggregateInputType = {
  id?: true
  order?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type NewsTagCountAggregateInputType = {
  id?: true
  order?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NewsTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsTag to aggregate.
   */
  where?: Prisma.NewsTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsTags to fetch.
   */
  orderBy?: Prisma.NewsTagOrderByWithRelationInput | Prisma.NewsTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NewsTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NewsTags
  **/
  _count?: true | NewsTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NewsTagAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NewsTagSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NewsTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NewsTagMaxAggregateInputType
}

export type GetNewsTagAggregateType<T extends NewsTagAggregateArgs> = {
      [P in keyof T & keyof AggregateNewsTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNewsTag[P]>
    : Prisma.GetScalarType<T[P], AggregateNewsTag[P]>
}




export type NewsTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewsTagWhereInput
  orderBy?: Prisma.NewsTagOrderByWithAggregationInput | Prisma.NewsTagOrderByWithAggregationInput[]
  by: Prisma.NewsTagScalarFieldEnum[] | Prisma.NewsTagScalarFieldEnum
  having?: Prisma.NewsTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NewsTagCountAggregateInputType | true
  _avg?: NewsTagAvgAggregateInputType
  _sum?: NewsTagSumAggregateInputType
  _min?: NewsTagMinAggregateInputType
  _max?: NewsTagMaxAggregateInputType
}

export type NewsTagGroupByOutputType = {
  id: string
  order: number
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: NewsTagCountAggregateOutputType | null
  _avg: NewsTagAvgAggregateOutputType | null
  _sum: NewsTagSumAggregateOutputType | null
  _min: NewsTagMinAggregateOutputType | null
  _max: NewsTagMaxAggregateOutputType | null
}

type GetNewsTagGroupByPayload<T extends NewsTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NewsTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NewsTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NewsTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NewsTagGroupByOutputType[P]>
      }
    >
  >



export type NewsTagWhereInput = {
  AND?: Prisma.NewsTagWhereInput | Prisma.NewsTagWhereInput[]
  OR?: Prisma.NewsTagWhereInput[]
  NOT?: Prisma.NewsTagWhereInput | Prisma.NewsTagWhereInput[]
  id?: Prisma.StringFilter<"NewsTag"> | string
  order?: Prisma.IntFilter<"NewsTag"> | number
  isActive?: Prisma.BoolFilter<"NewsTag"> | boolean
  createdAt?: Prisma.DateTimeFilter<"NewsTag"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NewsTag"> | Date | string
  news?: Prisma.NewsToTagListRelationFilter
}

export type NewsTagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  news?: Prisma.NewsToTagOrderByRelationAggregateInput
  _relevance?: Prisma.NewsTagOrderByRelevanceInput
}

export type NewsTagWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NewsTagWhereInput | Prisma.NewsTagWhereInput[]
  OR?: Prisma.NewsTagWhereInput[]
  NOT?: Prisma.NewsTagWhereInput | Prisma.NewsTagWhereInput[]
  order?: Prisma.IntFilter<"NewsTag"> | number
  isActive?: Prisma.BoolFilter<"NewsTag"> | boolean
  createdAt?: Prisma.DateTimeFilter<"NewsTag"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NewsTag"> | Date | string
  news?: Prisma.NewsToTagListRelationFilter
}, "id">

export type NewsTagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NewsTagCountOrderByAggregateInput
  _avg?: Prisma.NewsTagAvgOrderByAggregateInput
  _max?: Prisma.NewsTagMaxOrderByAggregateInput
  _min?: Prisma.NewsTagMinOrderByAggregateInput
  _sum?: Prisma.NewsTagSumOrderByAggregateInput
}

export type NewsTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.NewsTagScalarWhereWithAggregatesInput | Prisma.NewsTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.NewsTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NewsTagScalarWhereWithAggregatesInput | Prisma.NewsTagScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NewsTag"> | string
  order?: Prisma.IntWithAggregatesFilter<"NewsTag"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"NewsTag"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NewsTag"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NewsTag"> | Date | string
}

export type NewsTagCreateInput = {
  id?: string
  order?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  news?: Prisma.NewsToTagCreateNestedManyWithoutTagInput
}

export type NewsTagUncheckedCreateInput = {
  id?: string
  order?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  news?: Prisma.NewsToTagUncheckedCreateNestedManyWithoutTagInput
}

export type NewsTagUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  news?: Prisma.NewsToTagUpdateManyWithoutTagNestedInput
}

export type NewsTagUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  news?: Prisma.NewsToTagUncheckedUpdateManyWithoutTagNestedInput
}

export type NewsTagCreateManyInput = {
  id?: string
  order?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NewsTagUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsTagUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsTagOrderByRelevanceInput = {
  fields: Prisma.NewsTagOrderByRelevanceFieldEnum | Prisma.NewsTagOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type NewsTagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NewsTagAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type NewsTagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NewsTagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NewsTagSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type NewsTagScalarRelationFilter = {
  is?: Prisma.NewsTagWhereInput
  isNot?: Prisma.NewsTagWhereInput
}

export type NewsTagCreateNestedOneWithoutNewsInput = {
  create?: Prisma.XOR<Prisma.NewsTagCreateWithoutNewsInput, Prisma.NewsTagUncheckedCreateWithoutNewsInput>
  connectOrCreate?: Prisma.NewsTagCreateOrConnectWithoutNewsInput
  connect?: Prisma.NewsTagWhereUniqueInput
}

export type NewsTagUpdateOneRequiredWithoutNewsNestedInput = {
  create?: Prisma.XOR<Prisma.NewsTagCreateWithoutNewsInput, Prisma.NewsTagUncheckedCreateWithoutNewsInput>
  connectOrCreate?: Prisma.NewsTagCreateOrConnectWithoutNewsInput
  upsert?: Prisma.NewsTagUpsertWithoutNewsInput
  connect?: Prisma.NewsTagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NewsTagUpdateToOneWithWhereWithoutNewsInput, Prisma.NewsTagUpdateWithoutNewsInput>, Prisma.NewsTagUncheckedUpdateWithoutNewsInput>
}

export type NewsTagCreateWithoutNewsInput = {
  id?: string
  order?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NewsTagUncheckedCreateWithoutNewsInput = {
  id?: string
  order?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NewsTagCreateOrConnectWithoutNewsInput = {
  where: Prisma.NewsTagWhereUniqueInput
  create: Prisma.XOR<Prisma.NewsTagCreateWithoutNewsInput, Prisma.NewsTagUncheckedCreateWithoutNewsInput>
}

export type NewsTagUpsertWithoutNewsInput = {
  update: Prisma.XOR<Prisma.NewsTagUpdateWithoutNewsInput, Prisma.NewsTagUncheckedUpdateWithoutNewsInput>
  create: Prisma.XOR<Prisma.NewsTagCreateWithoutNewsInput, Prisma.NewsTagUncheckedCreateWithoutNewsInput>
  where?: Prisma.NewsTagWhereInput
}

export type NewsTagUpdateToOneWithWhereWithoutNewsInput = {
  where?: Prisma.NewsTagWhereInput
  data: Prisma.XOR<Prisma.NewsTagUpdateWithoutNewsInput, Prisma.NewsTagUncheckedUpdateWithoutNewsInput>
}

export type NewsTagUpdateWithoutNewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NewsTagUncheckedUpdateWithoutNewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type NewsTagCountOutputType
 */

export type NewsTagCountOutputType = {
  news: number
}

export type NewsTagCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  news?: boolean | NewsTagCountOutputTypeCountNewsArgs
}

/**
 * NewsTagCountOutputType without action
 */
export type NewsTagCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTagCountOutputType
   */
  select?: Prisma.NewsTagCountOutputTypeSelect<ExtArgs> | null
}

/**
 * NewsTagCountOutputType without action
 */
export type NewsTagCountOutputTypeCountNewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NewsToTagWhereInput
}


export type NewsTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  order?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  news?: boolean | Prisma.NewsTag$newsArgs<ExtArgs>
  _count?: boolean | Prisma.NewsTagCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["newsTag"]>



export type NewsTagSelectScalar = {
  id?: boolean
  order?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NewsTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "order" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["newsTag"]>
export type NewsTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  news?: boolean | Prisma.NewsTag$newsArgs<ExtArgs>
  _count?: boolean | Prisma.NewsTagCountOutputTypeDefaultArgs<ExtArgs>
}

export type $NewsTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NewsTag"
  objects: {
    news: Prisma.$NewsToTagPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    order: number
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["newsTag"]>
  composites: {}
}

export type NewsTagGetPayload<S extends boolean | null | undefined | NewsTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NewsTagPayload, S>

export type NewsTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NewsTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NewsTagCountAggregateInputType | true
  }

export interface NewsTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NewsTag'], meta: { name: 'NewsTag' } }
  /**
   * Find zero or one NewsTag that matches the filter.
   * @param {NewsTagFindUniqueArgs} args - Arguments to find a NewsTag
   * @example
   * // Get one NewsTag
   * const newsTag = await prisma.newsTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NewsTagFindUniqueArgs>(args: Prisma.SelectSubset<T, NewsTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NewsTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NewsTagFindUniqueOrThrowArgs} args - Arguments to find a NewsTag
   * @example
   * // Get one NewsTag
   * const newsTag = await prisma.newsTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NewsTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NewsTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagFindFirstArgs} args - Arguments to find a NewsTag
   * @example
   * // Get one NewsTag
   * const newsTag = await prisma.newsTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NewsTagFindFirstArgs>(args?: Prisma.SelectSubset<T, NewsTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NewsTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagFindFirstOrThrowArgs} args - Arguments to find a NewsTag
   * @example
   * // Get one NewsTag
   * const newsTag = await prisma.newsTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NewsTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NewsTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NewsTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NewsTags
   * const newsTags = await prisma.newsTag.findMany()
   * 
   * // Get first 10 NewsTags
   * const newsTags = await prisma.newsTag.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const newsTagWithIdOnly = await prisma.newsTag.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NewsTagFindManyArgs>(args?: Prisma.SelectSubset<T, NewsTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NewsTag.
   * @param {NewsTagCreateArgs} args - Arguments to create a NewsTag.
   * @example
   * // Create one NewsTag
   * const NewsTag = await prisma.newsTag.create({
   *   data: {
   *     // ... data to create a NewsTag
   *   }
   * })
   * 
   */
  create<T extends NewsTagCreateArgs>(args: Prisma.SelectSubset<T, NewsTagCreateArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NewsTags.
   * @param {NewsTagCreateManyArgs} args - Arguments to create many NewsTags.
   * @example
   * // Create many NewsTags
   * const newsTag = await prisma.newsTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NewsTagCreateManyArgs>(args?: Prisma.SelectSubset<T, NewsTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a NewsTag.
   * @param {NewsTagDeleteArgs} args - Arguments to delete one NewsTag.
   * @example
   * // Delete one NewsTag
   * const NewsTag = await prisma.newsTag.delete({
   *   where: {
   *     // ... filter to delete one NewsTag
   *   }
   * })
   * 
   */
  delete<T extends NewsTagDeleteArgs>(args: Prisma.SelectSubset<T, NewsTagDeleteArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NewsTag.
   * @param {NewsTagUpdateArgs} args - Arguments to update one NewsTag.
   * @example
   * // Update one NewsTag
   * const newsTag = await prisma.newsTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NewsTagUpdateArgs>(args: Prisma.SelectSubset<T, NewsTagUpdateArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NewsTags.
   * @param {NewsTagDeleteManyArgs} args - Arguments to filter NewsTags to delete.
   * @example
   * // Delete a few NewsTags
   * const { count } = await prisma.newsTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NewsTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, NewsTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NewsTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NewsTags
   * const newsTag = await prisma.newsTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NewsTagUpdateManyArgs>(args: Prisma.SelectSubset<T, NewsTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one NewsTag.
   * @param {NewsTagUpsertArgs} args - Arguments to update or create a NewsTag.
   * @example
   * // Update or create a NewsTag
   * const newsTag = await prisma.newsTag.upsert({
   *   create: {
   *     // ... data to create a NewsTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NewsTag we want to update
   *   }
   * })
   */
  upsert<T extends NewsTagUpsertArgs>(args: Prisma.SelectSubset<T, NewsTagUpsertArgs<ExtArgs>>): Prisma.Prisma__NewsTagClient<runtime.Types.Result.GetResult<Prisma.$NewsTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NewsTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagCountArgs} args - Arguments to filter NewsTags to count.
   * @example
   * // Count the number of NewsTags
   * const count = await prisma.newsTag.count({
   *   where: {
   *     // ... the filter for the NewsTags we want to count
   *   }
   * })
  **/
  count<T extends NewsTagCountArgs>(
    args?: Prisma.Subset<T, NewsTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NewsTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NewsTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NewsTagAggregateArgs>(args: Prisma.Subset<T, NewsTagAggregateArgs>): Prisma.PrismaPromise<GetNewsTagAggregateType<T>>

  /**
   * Group by NewsTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NewsTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NewsTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NewsTagGroupByArgs['orderBy'] }
      : { orderBy?: NewsTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NewsTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNewsTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NewsTag model
 */
readonly fields: NewsTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NewsTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NewsTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  news<T extends Prisma.NewsTag$newsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NewsTag$newsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NewsToTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NewsTag model
 */
export interface NewsTagFieldRefs {
  readonly id: Prisma.FieldRef<"NewsTag", 'String'>
  readonly order: Prisma.FieldRef<"NewsTag", 'Int'>
  readonly isActive: Prisma.FieldRef<"NewsTag", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"NewsTag", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NewsTag", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NewsTag findUnique
 */
export type NewsTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsTag to fetch.
   */
  where: Prisma.NewsTagWhereUniqueInput
}

/**
 * NewsTag findUniqueOrThrow
 */
export type NewsTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsTag to fetch.
   */
  where: Prisma.NewsTagWhereUniqueInput
}

/**
 * NewsTag findFirst
 */
export type NewsTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsTag to fetch.
   */
  where?: Prisma.NewsTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsTags to fetch.
   */
  orderBy?: Prisma.NewsTagOrderByWithRelationInput | Prisma.NewsTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsTags.
   */
  cursor?: Prisma.NewsTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsTags.
   */
  distinct?: Prisma.NewsTagScalarFieldEnum | Prisma.NewsTagScalarFieldEnum[]
}

/**
 * NewsTag findFirstOrThrow
 */
export type NewsTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsTag to fetch.
   */
  where?: Prisma.NewsTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsTags to fetch.
   */
  orderBy?: Prisma.NewsTagOrderByWithRelationInput | Prisma.NewsTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NewsTags.
   */
  cursor?: Prisma.NewsTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NewsTags.
   */
  distinct?: Prisma.NewsTagScalarFieldEnum | Prisma.NewsTagScalarFieldEnum[]
}

/**
 * NewsTag findMany
 */
export type NewsTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * Filter, which NewsTags to fetch.
   */
  where?: Prisma.NewsTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NewsTags to fetch.
   */
  orderBy?: Prisma.NewsTagOrderByWithRelationInput | Prisma.NewsTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NewsTags.
   */
  cursor?: Prisma.NewsTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NewsTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NewsTags.
   */
  skip?: number
  distinct?: Prisma.NewsTagScalarFieldEnum | Prisma.NewsTagScalarFieldEnum[]
}

/**
 * NewsTag create
 */
export type NewsTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * The data needed to create a NewsTag.
   */
  data: Prisma.XOR<Prisma.NewsTagCreateInput, Prisma.NewsTagUncheckedCreateInput>
}

/**
 * NewsTag createMany
 */
export type NewsTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NewsTags.
   */
  data: Prisma.NewsTagCreateManyInput | Prisma.NewsTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NewsTag update
 */
export type NewsTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * The data needed to update a NewsTag.
   */
  data: Prisma.XOR<Prisma.NewsTagUpdateInput, Prisma.NewsTagUncheckedUpdateInput>
  /**
   * Choose, which NewsTag to update.
   */
  where: Prisma.NewsTagWhereUniqueInput
}

/**
 * NewsTag updateMany
 */
export type NewsTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NewsTags.
   */
  data: Prisma.XOR<Prisma.NewsTagUpdateManyMutationInput, Prisma.NewsTagUncheckedUpdateManyInput>
  /**
   * Filter which NewsTags to update
   */
  where?: Prisma.NewsTagWhereInput
  /**
   * Limit how many NewsTags to update.
   */
  limit?: number
}

/**
 * NewsTag upsert
 */
export type NewsTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * The filter to search for the NewsTag to update in case it exists.
   */
  where: Prisma.NewsTagWhereUniqueInput
  /**
   * In case the NewsTag found by the `where` argument doesn't exist, create a new NewsTag with this data.
   */
  create: Prisma.XOR<Prisma.NewsTagCreateInput, Prisma.NewsTagUncheckedCreateInput>
  /**
   * In case the NewsTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NewsTagUpdateInput, Prisma.NewsTagUncheckedUpdateInput>
}

/**
 * NewsTag delete
 */
export type NewsTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
  /**
   * Filter which NewsTag to delete.
   */
  where: Prisma.NewsTagWhereUniqueInput
}

/**
 * NewsTag deleteMany
 */
export type NewsTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NewsTags to delete
   */
  where?: Prisma.NewsTagWhereInput
  /**
   * Limit how many NewsTags to delete.
   */
  limit?: number
}

/**
 * NewsTag.news
 */
export type NewsTag$newsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsToTag
   */
  select?: Prisma.NewsToTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsToTag
   */
  omit?: Prisma.NewsToTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsToTagInclude<ExtArgs> | null
  where?: Prisma.NewsToTagWhereInput
  orderBy?: Prisma.NewsToTagOrderByWithRelationInput | Prisma.NewsToTagOrderByWithRelationInput[]
  cursor?: Prisma.NewsToTagWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NewsToTagScalarFieldEnum | Prisma.NewsToTagScalarFieldEnum[]
}

/**
 * NewsTag without action
 */
export type NewsTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NewsTag
   */
  select?: Prisma.NewsTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NewsTag
   */
  omit?: Prisma.NewsTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NewsTagInclude<ExtArgs> | null
}
