
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceItem
 * 
 */
export type ServiceItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceItemPayload>

export type AggregateServiceItem = {
  _count: ServiceItemCountAggregateOutputType | null
  _min: ServiceItemMinAggregateOutputType | null
  _max: ServiceItemMaxAggregateOutputType | null
}

export type ServiceItemMinAggregateOutputType = {
  id: string | null
  categoryId: string | null
  name: string | null
  slug: string | null
  description: string | null
  image: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ServiceItemMaxAggregateOutputType = {
  id: string | null
  categoryId: string | null
  name: string | null
  slug: string | null
  description: string | null
  image: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ServiceItemCountAggregateOutputType = {
  id: number
  categoryId: number
  name: number
  slug: number
  description: number
  image: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ServiceItemMinAggregateInputType = {
  id?: true
  categoryId?: true
  name?: true
  slug?: true
  description?: true
  image?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type ServiceItemMaxAggregateInputType = {
  id?: true
  categoryId?: true
  name?: true
  slug?: true
  description?: true
  image?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type ServiceItemCountAggregateInputType = {
  id?: true
  categoryId?: true
  name?: true
  slug?: true
  description?: true
  image?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ServiceItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceItem to aggregate.
   */
  where?: Prisma.ServiceItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceItems to fetch.
   */
  orderBy?: Prisma.ServiceItemOrderByWithRelationInput | Prisma.ServiceItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceItems
  **/
  _count?: true | ServiceItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceItemMaxAggregateInputType
}

export type GetServiceItemAggregateType<T extends ServiceItemAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceItem[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceItem[P]>
}




export type ServiceItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceItemWhereInput
  orderBy?: Prisma.ServiceItemOrderByWithAggregationInput | Prisma.ServiceItemOrderByWithAggregationInput[]
  by: Prisma.ServiceItemScalarFieldEnum[] | Prisma.ServiceItemScalarFieldEnum
  having?: Prisma.ServiceItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceItemCountAggregateInputType | true
  _min?: ServiceItemMinAggregateInputType
  _max?: ServiceItemMaxAggregateInputType
}

export type ServiceItemGroupByOutputType = {
  id: string
  categoryId: string | null
  name: string
  slug: string
  description: string | null
  image: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: ServiceItemCountAggregateOutputType | null
  _min: ServiceItemMinAggregateOutputType | null
  _max: ServiceItemMaxAggregateOutputType | null
}

type GetServiceItemGroupByPayload<T extends ServiceItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceItemGroupByOutputType[P]>
      }
    >
  >



export type ServiceItemWhereInput = {
  AND?: Prisma.ServiceItemWhereInput | Prisma.ServiceItemWhereInput[]
  OR?: Prisma.ServiceItemWhereInput[]
  NOT?: Prisma.ServiceItemWhereInput | Prisma.ServiceItemWhereInput[]
  id?: Prisma.StringFilter<"ServiceItem"> | string
  categoryId?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  name?: Prisma.StringFilter<"ServiceItem"> | string
  slug?: Prisma.StringFilter<"ServiceItem"> | string
  description?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  image?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  isActive?: Prisma.BoolFilter<"ServiceItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ServiceItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceItem"> | Date | string
  category?: Prisma.XOR<Prisma.ServiceCategoryNullableScalarRelationFilter, Prisma.ServiceCategoryWhereInput> | null
}

export type ServiceItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  category?: Prisma.ServiceCategoryOrderByWithRelationInput
  _relevance?: Prisma.ServiceItemOrderByRelevanceInput
}

export type ServiceItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.ServiceItemWhereInput | Prisma.ServiceItemWhereInput[]
  OR?: Prisma.ServiceItemWhereInput[]
  NOT?: Prisma.ServiceItemWhereInput | Prisma.ServiceItemWhereInput[]
  categoryId?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  name?: Prisma.StringFilter<"ServiceItem"> | string
  description?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  image?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  isActive?: Prisma.BoolFilter<"ServiceItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ServiceItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceItem"> | Date | string
  category?: Prisma.XOR<Prisma.ServiceCategoryNullableScalarRelationFilter, Prisma.ServiceCategoryWhereInput> | null
}, "id" | "slug">

export type ServiceItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ServiceItemCountOrderByAggregateInput
  _max?: Prisma.ServiceItemMaxOrderByAggregateInput
  _min?: Prisma.ServiceItemMinOrderByAggregateInput
}

export type ServiceItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceItemScalarWhereWithAggregatesInput | Prisma.ServiceItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceItemScalarWhereWithAggregatesInput | Prisma.ServiceItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServiceItem"> | string
  categoryId?: Prisma.StringNullableWithAggregatesFilter<"ServiceItem"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"ServiceItem"> | string
  slug?: Prisma.StringWithAggregatesFilter<"ServiceItem"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ServiceItem"> | string | null
  image?: Prisma.StringNullableWithAggregatesFilter<"ServiceItem"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"ServiceItem"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceItem"> | Date | string
}

export type ServiceItemCreateInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  image?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  category?: Prisma.ServiceCategoryCreateNestedOneWithoutItemsInput
}

export type ServiceItemUncheckedCreateInput = {
  id?: string
  categoryId?: string | null
  name: string
  slug: string
  description?: string | null
  image?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.ServiceCategoryUpdateOneWithoutItemsNestedInput
}

export type ServiceItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceItemCreateManyInput = {
  id?: string
  categoryId?: string | null
  name: string
  slug: string
  description?: string | null
  image?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceItemListRelationFilter = {
  every?: Prisma.ServiceItemWhereInput
  some?: Prisma.ServiceItemWhereInput
  none?: Prisma.ServiceItemWhereInput
}

export type ServiceItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceItemOrderByRelevanceInput = {
  fields: Prisma.ServiceItemOrderByRelevanceFieldEnum | Prisma.ServiceItemOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ServiceItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  image?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  image?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  image?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceItemCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ServiceItemCreateWithoutCategoryInput, Prisma.ServiceItemUncheckedCreateWithoutCategoryInput> | Prisma.ServiceItemCreateWithoutCategoryInput[] | Prisma.ServiceItemUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ServiceItemCreateOrConnectWithoutCategoryInput | Prisma.ServiceItemCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ServiceItemCreateManyCategoryInputEnvelope
  connect?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
}

export type ServiceItemUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ServiceItemCreateWithoutCategoryInput, Prisma.ServiceItemUncheckedCreateWithoutCategoryInput> | Prisma.ServiceItemCreateWithoutCategoryInput[] | Prisma.ServiceItemUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ServiceItemCreateOrConnectWithoutCategoryInput | Prisma.ServiceItemCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ServiceItemCreateManyCategoryInputEnvelope
  connect?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
}

export type ServiceItemUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceItemCreateWithoutCategoryInput, Prisma.ServiceItemUncheckedCreateWithoutCategoryInput> | Prisma.ServiceItemCreateWithoutCategoryInput[] | Prisma.ServiceItemUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ServiceItemCreateOrConnectWithoutCategoryInput | Prisma.ServiceItemCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ServiceItemUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ServiceItemUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ServiceItemCreateManyCategoryInputEnvelope
  set?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  disconnect?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  delete?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  connect?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  update?: Prisma.ServiceItemUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ServiceItemUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ServiceItemUpdateManyWithWhereWithoutCategoryInput | Prisma.ServiceItemUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ServiceItemScalarWhereInput | Prisma.ServiceItemScalarWhereInput[]
}

export type ServiceItemUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceItemCreateWithoutCategoryInput, Prisma.ServiceItemUncheckedCreateWithoutCategoryInput> | Prisma.ServiceItemCreateWithoutCategoryInput[] | Prisma.ServiceItemUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ServiceItemCreateOrConnectWithoutCategoryInput | Prisma.ServiceItemCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ServiceItemUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ServiceItemUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ServiceItemCreateManyCategoryInputEnvelope
  set?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  disconnect?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  delete?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  connect?: Prisma.ServiceItemWhereUniqueInput | Prisma.ServiceItemWhereUniqueInput[]
  update?: Prisma.ServiceItemUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ServiceItemUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ServiceItemUpdateManyWithWhereWithoutCategoryInput | Prisma.ServiceItemUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ServiceItemScalarWhereInput | Prisma.ServiceItemScalarWhereInput[]
}

export type ServiceItemCreateWithoutCategoryInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  image?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceItemUncheckedCreateWithoutCategoryInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  image?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceItemCreateOrConnectWithoutCategoryInput = {
  where: Prisma.ServiceItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceItemCreateWithoutCategoryInput, Prisma.ServiceItemUncheckedCreateWithoutCategoryInput>
}

export type ServiceItemCreateManyCategoryInputEnvelope = {
  data: Prisma.ServiceItemCreateManyCategoryInput | Prisma.ServiceItemCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type ServiceItemUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ServiceItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceItemUpdateWithoutCategoryInput, Prisma.ServiceItemUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.ServiceItemCreateWithoutCategoryInput, Prisma.ServiceItemUncheckedCreateWithoutCategoryInput>
}

export type ServiceItemUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ServiceItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceItemUpdateWithoutCategoryInput, Prisma.ServiceItemUncheckedUpdateWithoutCategoryInput>
}

export type ServiceItemUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.ServiceItemScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceItemUpdateManyMutationInput, Prisma.ServiceItemUncheckedUpdateManyWithoutCategoryInput>
}

export type ServiceItemScalarWhereInput = {
  AND?: Prisma.ServiceItemScalarWhereInput | Prisma.ServiceItemScalarWhereInput[]
  OR?: Prisma.ServiceItemScalarWhereInput[]
  NOT?: Prisma.ServiceItemScalarWhereInput | Prisma.ServiceItemScalarWhereInput[]
  id?: Prisma.StringFilter<"ServiceItem"> | string
  categoryId?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  name?: Prisma.StringFilter<"ServiceItem"> | string
  slug?: Prisma.StringFilter<"ServiceItem"> | string
  description?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  image?: Prisma.StringNullableFilter<"ServiceItem"> | string | null
  isActive?: Prisma.BoolFilter<"ServiceItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ServiceItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceItem"> | Date | string
}

export type ServiceItemCreateManyCategoryInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  image?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceItemUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceItemUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceItemUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ServiceItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  image?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  category?: boolean | Prisma.ServiceItem$categoryArgs<ExtArgs>
}, ExtArgs["result"]["serviceItem"]>



export type ServiceItemSelectScalar = {
  id?: boolean
  categoryId?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  image?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ServiceItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "categoryId" | "name" | "slug" | "description" | "image" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["serviceItem"]>
export type ServiceItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.ServiceItem$categoryArgs<ExtArgs>
}

export type $ServiceItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceItem"
  objects: {
    category: Prisma.$ServiceCategoryPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    categoryId: string | null
    name: string
    slug: string
    description: string | null
    image: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["serviceItem"]>
  composites: {}
}

export type ServiceItemGetPayload<S extends boolean | null | undefined | ServiceItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload, S>

export type ServiceItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceItemCountAggregateInputType | true
  }

export interface ServiceItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceItem'], meta: { name: 'ServiceItem' } }
  /**
   * Find zero or one ServiceItem that matches the filter.
   * @param {ServiceItemFindUniqueArgs} args - Arguments to find a ServiceItem
   * @example
   * // Get one ServiceItem
   * const serviceItem = await prisma.serviceItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceItemFindUniqueOrThrowArgs} args - Arguments to find a ServiceItem
   * @example
   * // Get one ServiceItem
   * const serviceItem = await prisma.serviceItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemFindFirstArgs} args - Arguments to find a ServiceItem
   * @example
   * // Get one ServiceItem
   * const serviceItem = await prisma.serviceItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemFindFirstOrThrowArgs} args - Arguments to find a ServiceItem
   * @example
   * // Get one ServiceItem
   * const serviceItem = await prisma.serviceItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceItems
   * const serviceItems = await prisma.serviceItem.findMany()
   * 
   * // Get first 10 ServiceItems
   * const serviceItems = await prisma.serviceItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceItemWithIdOnly = await prisma.serviceItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceItemFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceItem.
   * @param {ServiceItemCreateArgs} args - Arguments to create a ServiceItem.
   * @example
   * // Create one ServiceItem
   * const ServiceItem = await prisma.serviceItem.create({
   *   data: {
   *     // ... data to create a ServiceItem
   *   }
   * })
   * 
   */
  create<T extends ServiceItemCreateArgs>(args: Prisma.SelectSubset<T, ServiceItemCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceItems.
   * @param {ServiceItemCreateManyArgs} args - Arguments to create many ServiceItems.
   * @example
   * // Create many ServiceItems
   * const serviceItem = await prisma.serviceItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ServiceItem.
   * @param {ServiceItemDeleteArgs} args - Arguments to delete one ServiceItem.
   * @example
   * // Delete one ServiceItem
   * const ServiceItem = await prisma.serviceItem.delete({
   *   where: {
   *     // ... filter to delete one ServiceItem
   *   }
   * })
   * 
   */
  delete<T extends ServiceItemDeleteArgs>(args: Prisma.SelectSubset<T, ServiceItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceItem.
   * @param {ServiceItemUpdateArgs} args - Arguments to update one ServiceItem.
   * @example
   * // Update one ServiceItem
   * const serviceItem = await prisma.serviceItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceItemUpdateArgs>(args: Prisma.SelectSubset<T, ServiceItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceItems.
   * @param {ServiceItemDeleteManyArgs} args - Arguments to filter ServiceItems to delete.
   * @example
   * // Delete a few ServiceItems
   * const { count } = await prisma.serviceItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceItems
   * const serviceItem = await prisma.serviceItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ServiceItem.
   * @param {ServiceItemUpsertArgs} args - Arguments to update or create a ServiceItem.
   * @example
   * // Update or create a ServiceItem
   * const serviceItem = await prisma.serviceItem.upsert({
   *   create: {
   *     // ... data to create a ServiceItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceItem we want to update
   *   }
   * })
   */
  upsert<T extends ServiceItemUpsertArgs>(args: Prisma.SelectSubset<T, ServiceItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceItemClient<runtime.Types.Result.GetResult<Prisma.$ServiceItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemCountArgs} args - Arguments to filter ServiceItems to count.
   * @example
   * // Count the number of ServiceItems
   * const count = await prisma.serviceItem.count({
   *   where: {
   *     // ... the filter for the ServiceItems we want to count
   *   }
   * })
  **/
  count<T extends ServiceItemCountArgs>(
    args?: Prisma.Subset<T, ServiceItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceItemAggregateArgs>(args: Prisma.Subset<T, ServiceItemAggregateArgs>): Prisma.PrismaPromise<GetServiceItemAggregateType<T>>

  /**
   * Group by ServiceItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceItemGroupByArgs['orderBy'] }
      : { orderBy?: ServiceItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceItem model
 */
readonly fields: ServiceItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.ServiceItem$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceItem$categoryArgs<ExtArgs>>): Prisma.Prisma__ServiceCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceItem model
 */
export interface ServiceItemFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceItem", 'String'>
  readonly categoryId: Prisma.FieldRef<"ServiceItem", 'String'>
  readonly name: Prisma.FieldRef<"ServiceItem", 'String'>
  readonly slug: Prisma.FieldRef<"ServiceItem", 'String'>
  readonly description: Prisma.FieldRef<"ServiceItem", 'String'>
  readonly image: Prisma.FieldRef<"ServiceItem", 'String'>
  readonly isActive: Prisma.FieldRef<"ServiceItem", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ServiceItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ServiceItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServiceItem findUnique
 */
export type ServiceItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * Filter, which ServiceItem to fetch.
   */
  where: Prisma.ServiceItemWhereUniqueInput
}

/**
 * ServiceItem findUniqueOrThrow
 */
export type ServiceItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * Filter, which ServiceItem to fetch.
   */
  where: Prisma.ServiceItemWhereUniqueInput
}

/**
 * ServiceItem findFirst
 */
export type ServiceItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * Filter, which ServiceItem to fetch.
   */
  where?: Prisma.ServiceItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceItems to fetch.
   */
  orderBy?: Prisma.ServiceItemOrderByWithRelationInput | Prisma.ServiceItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceItems.
   */
  cursor?: Prisma.ServiceItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceItems.
   */
  distinct?: Prisma.ServiceItemScalarFieldEnum | Prisma.ServiceItemScalarFieldEnum[]
}

/**
 * ServiceItem findFirstOrThrow
 */
export type ServiceItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * Filter, which ServiceItem to fetch.
   */
  where?: Prisma.ServiceItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceItems to fetch.
   */
  orderBy?: Prisma.ServiceItemOrderByWithRelationInput | Prisma.ServiceItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceItems.
   */
  cursor?: Prisma.ServiceItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceItems.
   */
  distinct?: Prisma.ServiceItemScalarFieldEnum | Prisma.ServiceItemScalarFieldEnum[]
}

/**
 * ServiceItem findMany
 */
export type ServiceItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * Filter, which ServiceItems to fetch.
   */
  where?: Prisma.ServiceItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceItems to fetch.
   */
  orderBy?: Prisma.ServiceItemOrderByWithRelationInput | Prisma.ServiceItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceItems.
   */
  cursor?: Prisma.ServiceItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceItems.
   */
  skip?: number
  distinct?: Prisma.ServiceItemScalarFieldEnum | Prisma.ServiceItemScalarFieldEnum[]
}

/**
 * ServiceItem create
 */
export type ServiceItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceItem.
   */
  data: Prisma.XOR<Prisma.ServiceItemCreateInput, Prisma.ServiceItemUncheckedCreateInput>
}

/**
 * ServiceItem createMany
 */
export type ServiceItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceItems.
   */
  data: Prisma.ServiceItemCreateManyInput | Prisma.ServiceItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceItem update
 */
export type ServiceItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceItem.
   */
  data: Prisma.XOR<Prisma.ServiceItemUpdateInput, Prisma.ServiceItemUncheckedUpdateInput>
  /**
   * Choose, which ServiceItem to update.
   */
  where: Prisma.ServiceItemWhereUniqueInput
}

/**
 * ServiceItem updateMany
 */
export type ServiceItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceItems.
   */
  data: Prisma.XOR<Prisma.ServiceItemUpdateManyMutationInput, Prisma.ServiceItemUncheckedUpdateManyInput>
  /**
   * Filter which ServiceItems to update
   */
  where?: Prisma.ServiceItemWhereInput
  /**
   * Limit how many ServiceItems to update.
   */
  limit?: number
}

/**
 * ServiceItem upsert
 */
export type ServiceItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceItem to update in case it exists.
   */
  where: Prisma.ServiceItemWhereUniqueInput
  /**
   * In case the ServiceItem found by the `where` argument doesn't exist, create a new ServiceItem with this data.
   */
  create: Prisma.XOR<Prisma.ServiceItemCreateInput, Prisma.ServiceItemUncheckedCreateInput>
  /**
   * In case the ServiceItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceItemUpdateInput, Prisma.ServiceItemUncheckedUpdateInput>
}

/**
 * ServiceItem delete
 */
export type ServiceItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
  /**
   * Filter which ServiceItem to delete.
   */
  where: Prisma.ServiceItemWhereUniqueInput
}

/**
 * ServiceItem deleteMany
 */
export type ServiceItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceItems to delete
   */
  where?: Prisma.ServiceItemWhereInput
  /**
   * Limit how many ServiceItems to delete.
   */
  limit?: number
}

/**
 * ServiceItem.category
 */
export type ServiceItem$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceCategory
   */
  select?: Prisma.ServiceCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceCategory
   */
  omit?: Prisma.ServiceCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceCategoryInclude<ExtArgs> | null
  where?: Prisma.ServiceCategoryWhereInput
}

/**
 * ServiceItem without action
 */
export type ServiceItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceItem
   */
  select?: Prisma.ServiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceItem
   */
  omit?: Prisma.ServiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceItemInclude<ExtArgs> | null
}
